project:
  type: website
  output-dir: docs  # Ensure Quarto builds into /docs for GitHub Pages
  resources:
    - graphics/sankey_plots2/lib/**

website:
  page-navigation: true
  title: "Citation Database Assessment"
  site-url: "https://laurenchenarides.github.io/data_usage_report/"
  repo-url: https://github.com/laurenchenarides/data_usage_report
  repo-actions: [edit, issue]
  
  page-footer: 
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "**AI Assistance Disclosure:** This website was developed with the assistance of artificial intelligence tools to enhance content creation, design, and user experience. All content has been reviewed and approved by our team to ensure accuracy and quality."

  sidebar:
    pinned: true
    align: center
    tools:
      - icon: github
        href: "https://github.com/laurenchenarides/data_usage_report"
        aria-label: "GitHub Repository"
    
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Report Summary
      - href: report.qmd
        text: Full Report
      - section: appendix.qmd
        text: "Appendices"
        contents:
          - href: appendices/terminology.qmd
            text: Terminology
          - href: appendices/workflow.qmd
            text: Workflow
            contents: 
            - href: appendices/workflow/step01/define_data_assets.qmd
              text: "Define Data Assets"
            - href: appendices/workflow/step02_01/extract_dataset_mentions.qmd
              text: "Extract Dataset Mentions"
            - href: appendices/workflow/step02_02/create_seed_corpus.qmd
              text: "Creating a Seed Corpus"
          - href: appendices/app_crosswalk.qmd # Summary of Scopus, OpenAlex, and Dimensions
            text: "Documentation"
          - href: appendices/app_institutions.qmd
            contents:
            - href: appendices/app_ipeds.qmd # Ming's work on IPEDS
            - href: appendices/app_msi.qmd # Ming's work on MSIs
      - href: webinar_questionnaire.qmd
        text: Questionnaire

      
format:
  html:
    toc: true  # Enables table of contents
    toc-depth: 3  # Adjust depth of TOC levels
    toc-location: left  # Options: left, right
    theme: default  # You can customize this
    number-sections: true  # Number sections if desired
    highlight-style: github  # Code highlighting style
    author-title: false
    
editor: source

execute:
  freeze: auto  # Ensures all references are updated

