## Scopus

### Journal Coverage {.unnumbered}

To analyze journal coverage in **Scopus**, we generate a dataset containing all unique journals that include at least one publication referencing Ag Census data. This dataset is built from an initial publication-level dataset, which captures individual research articles mentioning Ag Census.

We construct the publication-level dataset for only Ag Census mentions using the following metadata from the publication-level data:

- Publication identifier (DOI)
- Journal name
- Publisher
- ISSN (International Standard Serial Number, a unique journal identifier)
- Dataset alias (alternate names used to reference Ag Census)
- Dyad (dataset mention pair)

This data structure follows the format outlined in the data schema (Figure XX). 

:::{.callout-note title="Crosswalk of Dataset Identifiers between Scopus and OpenAlex" collapse=true}
Scopus assigns multiple identifiers to the same dataset depending on how it is reported, rather than a single, standardized identifier. Therefore, the authors create a crosswalk between Scopus and OpenAlex so that each dataset can have one common identifier.

[Link to crosswalk file](../appendices/app_crosswalk_data_id.qmd) 
:::

After assembling the publication-level dataset, the final step in preparing the Scopus journal-level dataset is to aggregate publications at the journal level based on their ISSN.

### Author Disambiguation {.unnumbered}

**COMING SOON**

### Institution Disambiguation{.unnumbered}

**COMING SOON**



