<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Appendices – Citation Database Assessment</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Citation Database Assessment</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Technical Report</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./appendices.html" aria-current="page"> 
<span class="menu-text">Appendices</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/laurenchenarides/compare_scopus_openalex_report"> <i class="bi bi-github" role="img" aria-label="GitHub Repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Appendices</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">Scopus Metadata File Description</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">OpenAlex Metadata File Description</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">Scopus Metadata File Description</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false">OpenAlex Metadata File Description</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-5" role="tab" aria-controls="tabset-1-5" aria-selected="false">Scopus Metadata File Description</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-6-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-6" role="tab" aria-controls="tabset-1-6" aria-selected="false">OpenAlex Metadata File Description</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p>This section describes the process of construction CSV files extracted from a SQL Server database. These files contain interconnected data about publications and datasets, specifically focusing on how datasets are mentioned within publications. The main goal is to enable you to analyze the relationships between publications and datasets, particularly those identified using specific search models.</p>
<section id="contents-of-the-csv-files" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="contents-of-the-csv-files"><span class="header-section-number">1</span> Contents of the CSV Files</h2>
<p>Below is a detailed explanation of each CSV file and how they relate to one another:</p>
<section id="publication.csv" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="publication.csv"><span class="header-section-number">1.1</span> <strong>publication.csv</strong></h3>
<ul>
<li><strong>Description</strong>: This file contains information about publications, which are the central entities in this dataset.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>id</code>: Unique identifier for each publication.</li>
<li><code>title</code>: Title of the publication.</li>
<li><code>doi</code>: Digital Object Identifier of the publication.</li>
<li><code>year</code> and <code>month</code>: Publication date.</li>
<li>Other metadata such as <code>citation_count</code>, <code>pub_type</code>, etc.</li>
</ul></li>
</ul>
<p><strong>Sample Data</strong>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 59%">
<col style="width: 22%">
<col style="width: 5%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th>id</th>
<th>title</th>
<th>doi</th>
<th>year</th>
<th>month</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>321613</td>
<td>New estimates for CRNA vacancies</td>
<td></td>
<td>2009</td>
<td>4</td>
</tr>
<tr class="even">
<td>321614</td>
<td>Crossing county lines: The impact of crash location and driver’s…</td>
<td>10.1016/j.aap.2006…</td>
<td>2006</td>
<td>7</td>
</tr>
</tbody>
</table>
</section>
<section id="dataset_alias.csv" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="dataset_alias.csv"><span class="header-section-number">1.2</span> <strong>dataset_alias.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Contains all the aliases (alternative names) of datasets. This helps in identifying datasets that might be referred to by different names in publications.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>alias_id</code>: Unique identifier for each alias.</li>
<li><code>parent_alias_id</code>: Identifies the main alias for a dataset. If <code>parent_alias_id</code> equals <code>alias_id</code>, it is the primary alias.</li>
<li><code>alias</code>: The alias name of the dataset.</li>
</ul></li>
</ul>
<p><strong>How to Use</strong>:</p>
<ul>
<li>To find the main alias of a dataset, look for rows where <code>alias_id</code> equals <code>parent_alias_id</code>.</li>
<li>To find all aliases of a dataset, filter by <code>parent_alias_id</code> corresponding to the main alias.</li>
</ul>
<p><strong>Sample Data</strong>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 20%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>id</th>
<th>alias_id</th>
<th>parent_alias_id</th>
<th>alias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1676</td>
<td>87</td>
<td>89</td>
<td>Census of Agriculture</td>
</tr>
<tr class="even">
<td>1673</td>
<td>12</td>
<td>282</td>
<td>ARMS Farm Financial and Crop Production Practices</td>
</tr>
</tbody>
</table>
</section>
<section id="dyad.csv" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="dyad.csv"><span class="header-section-number">1.3</span> <strong>dyad.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Represents the mentions of dataset aliases found within publications. Acts as a linking table between <code>publication.csv</code> and <code>dataset_alias.csv</code>.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>id</code>: Unique identifier for each dyad (mention).</li>
<li><code>publication_id</code>: References the <code>id</code> in <code>publication.csv</code>.</li>
<li><code>alias_id</code>: References the <code>alias_id</code> in <code>dataset_alias.csv</code>.</li>
<li><code>mention_candidate</code>: The actual text mentioning the dataset in the publication.</li>
</ul></li>
</ul>
<p><strong>Sample Data</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>publication_id</th>
<th>alias_id</th>
<th>mention_candidate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2569</td>
<td>1211491</td>
<td>87</td>
<td>census of agriculture</td>
</tr>
<tr class="even">
<td>2573</td>
<td>1199598</td>
<td>88</td>
<td>usda census of agriculture</td>
</tr>
</tbody>
</table>
</section>
<section id="model.csv" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="model.csv"><span class="header-section-number">1.4</span> <strong>model.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Lists the different models or methods used to identify dataset mentions within publications.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>id</code>: Unique identifier for each model.</li>
<li><code>name</code>: Name of the model (e.g., <code>string_matching</code>, <code>refmatch</code>).</li>
</ul></li>
</ul>
<p><strong>Relevant Models</strong>:</p>
<ul>
<li><strong>Model ID 1</strong>: <code>string_matching</code></li>
<li><strong>Model ID 5</strong>: <code>refmatch</code></li>
</ul>
<p>These are the models we are focusing on to compare with data extracted from OpenAlex, as no Kaggle model has been applied there.</p>
<p><strong>Sample Data</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>string_matching</td>
</tr>
<tr class="even">
<td>5</td>
<td>refmatch</td>
</tr>
</tbody>
</table>
</section>
<section id="dyad_model.csv" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="dyad_model.csv"><span class="header-section-number">1.5</span> <strong>dyad_model.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Connects dyads with the models that identified them. Allows filtering dyads based on the models used.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>dyad_id</code>: References the <code>id</code> in <code>dyad.csv</code>.</li>
<li><code>model_id</code>: References the <code>id</code> in <code>model.csv</code>.</li>
</ul></li>
</ul>
<p><strong>How to Use</strong>:</p>
<ul>
<li>To filter dyads (and thus publications) identified by specific models, perform an inner join with <code>dyad.csv</code> on <code>dyad_id</code> and filter by <code>model_id</code>.</li>
</ul>
<p><strong>Sample Data</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>dyad_id</th>
<th>model_id</th>
<th>score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4928</td>
<td>2569</td>
<td>1</td>
<td>2.0</td>
</tr>
<tr class="even">
<td>4929</td>
<td>2569</td>
<td>4</td>
<td>1.0</td>
</tr>
<tr class="odd">
<td>4930</td>
<td>2569</td>
<td>2</td>
<td>1.0</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="how-to-extract-publications-for-a-specific-dataset" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="how-to-extract-publications-for-a-specific-dataset"><span class="header-section-number">2</span> How to Extract Publications for a Specific Dataset</h2>
<p>To find all publications associated with a particular dataset, such as the <strong>NASS Census of Agriculture</strong>, follow these steps:</p>
<ol type="1">
<li><p><strong>Identify the Main Alias</strong>:</p>
<ul>
<li>Find the <code>alias_id</code> where <code>alias_id</code> equals <code>parent_alias_id</code> for the dataset.</li>
<li>For <strong>NASS Census of Agriculture</strong>, the main alias has <code>alias_id</code> = <strong>89</strong>.</li>
</ul></li>
<li><p><strong>Get All Aliases</strong>:</p>
<ul>
<li>In <code>dataset_alias.csv</code>, filter rows where <code>parent_alias_id</code> equals <strong>89</strong>.</li>
<li>This gives you all aliases associated with the <strong>NASS Census of Agriculture</strong> dataset.</li>
</ul></li>
<li><p><strong>Link Aliases to Publications</strong>:</p>
<ul>
<li>In <code>dyad.csv</code>, filter rows where <code>alias_id</code> matches any of the <code>alias_id</code>s obtained in step 2.</li>
<li>This will give you <code>publication_id</code>s of publications mentioning any alias of the dataset.</li>
</ul></li>
<li><p><strong>Retrieve Publication Details</strong>:</p>
<ul>
<li>Using the <code>publication_id</code>s from step 3, retrieve the corresponding records from <code>publication.csv</code>.</li>
</ul></li>
</ol>
</section>
<section id="filtering-publications-by-specific-models" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="filtering-publications-by-specific-models"><span class="header-section-number">3</span> Filtering Publications by Specific Models</h2>
<p>Since we’re interested in mentions identified by the <strong><code>string_matching</code></strong> and <strong><code>refmatch</code></strong> models (models with <code>id</code> 1 and 5), follow these steps:</p>
<ol type="1">
<li><p><strong>Filter Dyads by Model</strong>:</p>
<ul>
<li>In <code>dyad_model.csv</code>, filter rows where <code>model_id</code> is <strong>1</strong> or <strong>5</strong>.</li>
<li>This gives you <code>dyad_id</code>s linked to these models.</li>
</ul></li>
<li><p><strong>Get Relevant Dyads</strong>:</p>
<ul>
<li>Perform an inner join with <code>dyad.csv</code> on <code>dyad_id</code>.</li>
<li>This filters dyads to only those identified by the specified models.</li>
</ul></li>
<li><p><strong>Proceed as Before</strong>:</p>
<ul>
<li>Continue with the steps in the previous section, but using the filtered dyads from step 2.</li>
</ul></li>
</ol>
</section>
<section id="practical-example" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="practical-example"><span class="header-section-number">4</span> Practical Example</h2>
<p><strong>Objective</strong>: Find all publications mentioning the <strong>NASS Census of Agriculture</strong> dataset using the <code>string_matching</code> and <code>refmatch</code> models.</p>
<p><strong>Steps</strong>:</p>
<ol type="1">
<li><p><strong>Find Main Alias ID</strong>:</p>
<ul>
<li>Main alias <code>alias_id</code> = <strong>89</strong>.</li>
</ul></li>
<li><p><strong>Get All Aliases</strong>:</p>
<ul>
<li>From <code>dataset_alias.csv</code>, extract all <code>alias_id</code>s where <code>parent_alias_id</code> = <strong>89</strong>.</li>
</ul></li>
<li><p><strong>Filter Dyads by Models</strong>:</p>
<ul>
<li>From <code>dyad_model.csv</code>, get <code>dyad_id</code>s where <code>model_id</code> is <strong>1</strong> or <strong>5</strong>.</li>
</ul></li>
<li><p><strong>Get Dyads for Dataset</strong>:</p>
<ul>
<li>From <code>dyad.csv</code>, select rows where:
<ul>
<li><code>alias_id</code> is in the list from step 2, and</li>
<li><code>id</code> (dyad_id) is in the list from step 3.</li>
</ul></li>
</ul></li>
<li><p><strong>Retrieve Publications</strong>:</p>
<ul>
<li>Use <code>publication_id</code>s from the filtered dyads to get detailed information from <code>publication.csv</code>.</li>
</ul></li>
</ol>
</section>
<section id="sample-data-illustration" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="sample-data-illustration"><span class="header-section-number">5</span> Sample Data Illustration</h2>
<p><strong>From <code>dataset_alias.csv</code></strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>alias_id</th>
<th>parent_alias_id</th>
<th>alias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>87</td>
<td>89</td>
<td>Census of Agriculture</td>
</tr>
<tr class="even">
<td>88</td>
<td>89</td>
<td>USDA Census of Agriculture</td>
</tr>
</tbody>
</table>
<p><strong>From <code>dyad.csv</code></strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>publication_id</th>
<th>alias_id</th>
<th>mention_candidate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2569</td>
<td>1211491</td>
<td>87</td>
<td>census of agriculture</td>
</tr>
<tr class="even">
<td>2573</td>
<td>1199598</td>
<td>88</td>
<td>usda census of agriculture</td>
</tr>
</tbody>
</table>
<p><strong>From <code>dyad_model.csv</code></strong> (filtered for <code>model_id</code> 1 or 5):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>dyad_id</th>
<th>model_id</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2569</td>
<td>1</td>
</tr>
<tr class="even">
<td>2573</td>
<td>5</td>
</tr>
</tbody>
</table>
<p><strong>Resulting Publications</strong>:</p>
<ul>
<li>Publications with <code>id</code> <strong>1211491</strong> and <strong>1199598</strong> from <code>publication.csv</code>.</li>
</ul>
</section>
<section id="conclusion" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">6</span> Conclusion</h2>
<p>By following the steps outlined above, you can effectively navigate the dataset to extract publications related to specific datasets and identified by particular models. This structured approach allows for targeted analysis and comparison with data from sources like OpenAlex.</p>
</section>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>This section describes the process of construction CSV files extracted from a SQL Server database. These files contain interconnected data about publications and datasets, specifically focusing on how datasets are mentioned within publications. The main goal is to enable you to analyze the relationships between publications and datasets, particularly those identified using specific search models.</p>
<p>Unlike the initial dataset from Scopus, the OpenAlex publications can be associated with multiple datasets. Two new files are introduced:</p>
<ul>
<li><strong>dataset.csv</strong>: Lists all datasets identified in OpenAlex. This contains details of all USDA datasets.</li>
<li><strong>publication_dataset_links.csv</strong>: Connects publications with one or more datasets in the OpenAlex data. Indicates which publications are associated with which datasets.</li>
</ul>
<p>The search in OpenAlex was performed using the same aliases and flag terms applied in the Scopus data, without any optimization. As a consequence, the “NASS Census of Agriculture” dataset currently shows fewer publications than in the previous sample due to this direct, unoptimized search approach.</p>
<section id="contents-of-the-csv-files-1" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="contents-of-the-csv-files-1"><span class="header-section-number">7</span> Contents of the CSV Files</h2>
<p>Below is a detailed explanation of the SQL Server-related CSV files and how they relate to one another:</p>
<section id="publication.csv-1" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="publication.csv-1"><span class="header-section-number">7.1</span> <strong>publication.csv</strong></h3>
<ul>
<li><strong>Description</strong>: This file contains information about publications, which are the central entities in this dataset.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>id</code>: Unique identifier for each publication.</li>
<li><code>title</code>: Title of the publication.</li>
<li><code>doi</code>: Digital Object Identifier of the publication.</li>
<li><code>year</code> and <code>month</code>: Publication date.</li>
<li>Other metadata such as <code>citation_count</code>, <code>pub_type</code>, etc.</li>
</ul></li>
</ul>
<p><strong>Sample Data</strong>:</p>
<!--\~~~markdown-->
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 59%">
<col style="width: 22%">
<col style="width: 5%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th>id</th>
<th>title</th>
<th>doi</th>
<th>year</th>
<th>month</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>321613</td>
<td>New estimates for CRNA vacancies</td>
<td></td>
<td>2009</td>
<td>4</td>
</tr>
<tr class="even">
<td>321614</td>
<td>Crossing county lines: The impact of crash location and driver’s…</td>
<td>10.1016/j.aap.2006…</td>
<td>2006</td>
<td>7</td>
</tr>
</tbody>
</table>
</section>
<section id="dataset_alias.csv-1" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="dataset_alias.csv-1"><span class="header-section-number">7.2</span> <strong>dataset_alias.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Contains all the aliases (alternative names) of datasets. This helps in identifying datasets that might be referred to by different names in publications.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>alias_id</code>: Unique identifier for each alias.</li>
<li><code>parent_alias_id</code>: Identifies the main alias for a dataset. If <code>parent_alias_id</code> equals <code>alias_id</code>, it is the primary alias.</li>
<li><code>alias</code>: The alias name of the dataset.</li>
</ul></li>
</ul>
<p><strong>How to Use</strong>:</p>
<ul>
<li>To find the main alias of a dataset, look for rows where <code>alias_id</code> equals <code>parent_alias_id</code>.</li>
<li>To find all aliases of a dataset, filter by <code>parent_alias_id</code> corresponding to the main alias.</li>
</ul>
<p><strong>Sample Data</strong>:</p>
<!--\~~~markdown-->
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 20%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>id</th>
<th>alias_id</th>
<th>parent_alias_id</th>
<th>alias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1676</td>
<td>87</td>
<td>89</td>
<td>Census of Agriculture</td>
</tr>
<tr class="even">
<td>1673</td>
<td>12</td>
<td>282</td>
<td>ARMS Farm Financial and Crop Production Practices</td>
</tr>
</tbody>
</table>
</section>
<section id="dyad.csv-1" class="level3" data-number="7.3">
<h3 data-number="7.3" class="anchored" data-anchor-id="dyad.csv-1"><span class="header-section-number">7.3</span> <strong>dyad.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Represents the mentions of dataset aliases found within publications. Acts as a linking table between <code>publication.csv</code> and <code>dataset_alias.csv</code>.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>id</code>: Unique identifier for each dyad (mention).</li>
<li><code>publication_id</code>: References the <code>id</code> in <code>publication.csv</code>.</li>
<li><code>alias_id</code>: References the <code>alias_id</code> in <code>dataset_alias.csv</code>.</li>
<li><code>mention_candidate</code>: The actual text mentioning the dataset in the publication.</li>
</ul></li>
</ul>
<p><strong>Sample Data</strong>:</p>
<!--\~~~markdown-->
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>publication_id</th>
<th>alias_id</th>
<th>mention_candidate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2569</td>
<td>1211491</td>
<td>87</td>
<td>census of agriculture</td>
</tr>
<tr class="even">
<td>2573</td>
<td>1199598</td>
<td>88</td>
<td>usda census of agriculture</td>
</tr>
</tbody>
</table>
</section>
<section id="model.csv-1" class="level3" data-number="7.4">
<h3 data-number="7.4" class="anchored" data-anchor-id="model.csv-1"><span class="header-section-number">7.4</span> <strong>model.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Lists the different models or methods used to identify dataset mentions within publications.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>id</code>: Unique identifier for each model.</li>
<li><code>name</code>: Name of the model (e.g., <code>string_matching</code>, <code>refmatch</code>).</li>
</ul></li>
</ul>
<p><strong>Relevant Models</strong>:</p>
<ul>
<li><strong>Model ID 1</strong>: <code>string_matching</code></li>
<li><strong>Model ID 5</strong>: <code>refmatch</code></li>
</ul>
<p>These are the models we are focusing on to compare with data extracted from OpenAlex, as no Kaggle model has been applied there.</p>
<p><strong>Sample Data</strong>:</p>
<!--\~~~markdown-->
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>string_matching</td>
</tr>
<tr class="even">
<td>5</td>
<td>refmatch</td>
</tr>
</tbody>
</table>
</section>
<section id="dyad_model.csv-1" class="level3" data-number="7.5">
<h3 data-number="7.5" class="anchored" data-anchor-id="dyad_model.csv-1"><span class="header-section-number">7.5</span> <strong>dyad_model.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Connects dyads with the models that identified them. Allows filtering dyads based on the models used.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>dyad_id</code>: References the <code>id</code> in <code>dyad.csv</code>.</li>
<li><code>model_id</code>: References the <code>id</code> in <code>model.csv</code>.</li>
</ul></li>
</ul>
<p><strong>How to Use</strong>:</p>
<ul>
<li>To filter dyads (and thus publications) identified by specific models, perform an inner join with <code>dyad.csv</code> on <code>dyad_id</code> and filter by <code>model_id</code>.</li>
</ul>
<p><strong>Sample Data</strong>:</p>
<!--\~~~markdown-->
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>dyad_id</th>
<th>model_id</th>
<th>score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4928</td>
<td>2569</td>
<td>1</td>
<td>2.0</td>
</tr>
<tr class="even">
<td>4929</td>
<td>2569</td>
<td>4</td>
<td>1.0</td>
</tr>
<tr class="odd">
<td>4930</td>
<td>2569</td>
<td>2</td>
<td>1.0</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="how-the-files-are-related" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="how-the-files-are-related"><span class="header-section-number">8</span> How the Files are Related</h2>
<p>The files are structured to represent entities (publications, journals, institutions, authors) and their relationships. The main publication data is in <code>publications_main.csv</code>, and the details about journals, institutions, and authors are in their respective files. The link files (<code>publication_journal_links.csv</code>, <code>publication_institution_links.csv</code>, <code>publication_author_links.csv</code>) represent the many-to-many relationships between publications and these entities.</p>
<p>By using the OpenAlex identifiers, you can join these files to perform comprehensive analyses. For example:</p>
<ul>
<li>To find all publications by a specific author, you can use <code>authors.csv</code> to find the author’s <code>author_openalex_id</code> and then use <code>publication_author_links.csv</code> to find the associated publications.</li>
<li>To analyze the distribution of publications across journals, you can join <code>publications_main.csv</code>, <code>publication_journal_links.csv</code>, and <code>journals.csv</code> on <code>publication_openalex_id</code> and <code>journal_openalex_id</code>.</li>
</ul>
</section>
<section id="how-to-extract-publications-for-a-specific-dataset-1" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="how-to-extract-publications-for-a-specific-dataset-1"><span class="header-section-number">9</span> How to Extract Publications for a Specific Dataset</h2>
<p>To find all publications associated with a particular dataset, such as the <strong>NASS Census of Agriculture</strong>, follow these steps:</p>
<ol type="1">
<li><p><strong>Identify the Main Alias</strong>:</p>
<ul>
<li>Find the <code>alias_id</code> where <code>alias_id</code> equals <code>parent_alias_id</code> for the dataset.</li>
<li>For <strong>NASS Census of Agriculture</strong>, the main alias has <code>alias_id</code> = <strong>89</strong>.</li>
</ul></li>
<li><p><strong>Get All Aliases</strong>:</p>
<ul>
<li>In <code>dataset_alias.csv</code>, filter rows where <code>parent_alias_id</code> equals <strong>89</strong>.</li>
<li>This gives you all aliases associated with the <strong>NASS Census of Agriculture</strong> dataset.</li>
</ul></li>
<li><p><strong>Link Aliases to Publications</strong>:</p>
<ul>
<li>In <code>dyad.csv</code>, filter rows where <code>alias_id</code> matches any of the <code>alias_id</code>s obtained in step 2.</li>
<li>This will give you <code>publication_id</code>s of publications mentioning any alias of the dataset.</li>
</ul></li>
<li><p><strong>Retrieve Publication Details</strong>:</p>
<ul>
<li>Using the <code>publication_id</code>s from step 3, retrieve the corresponding records from <code>publication.csv</code>.</li>
</ul></li>
</ol>
</section>
<section id="filtering-publications-by-specific-models-1" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="filtering-publications-by-specific-models-1"><span class="header-section-number">10</span> Filtering Publications by Specific Models</h2>
<p>Since we’re interested in mentions identified by the <strong><code>string_matching</code></strong> and <strong><code>refmatch</code></strong> models (models with <code>id</code> 1 and 5), follow these steps:</p>
<ol type="1">
<li><p><strong>Filter Dyads by Model</strong>:</p>
<ul>
<li>In <code>dyad_model.csv</code>, filter rows where <code>model_id</code> is <strong>1</strong> or <strong>5</strong>.</li>
<li>This gives you <code>dyad_id</code>s linked to these models.</li>
</ul></li>
<li><p><strong>Get Relevant Dyads</strong>:</p>
<ul>
<li>Perform an inner join with <code>dyad.csv</code> on <code>dyad_id</code>.</li>
<li>This filters dyads to only those identified by the specified models.</li>
</ul></li>
<li><p><strong>Proceed as Before</strong>:</p>
<ul>
<li>Continue with the steps in the previous section, but using the filtered dyads from step 2.</li>
</ul></li>
</ol>
</section>
<section id="practical-example-1" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="practical-example-1"><span class="header-section-number">11</span> Practical Example</h2>
<p><strong>Objective</strong>: Find all publications mentioning the <strong>NASS Census of Agriculture</strong> dataset using the <code>string_matching</code> and <code>refmatch</code> models.</p>
<p><strong>Steps</strong>:</p>
<ol type="1">
<li><p><strong>Find Main Alias ID</strong>:</p>
<ul>
<li>Main alias <code>alias_id</code> = <strong>89</strong>.</li>
</ul></li>
<li><p><strong>Get All Aliases</strong>:</p>
<ul>
<li>From <code>dataset_alias.csv</code>, extract all <code>alias_id</code>s where <code>parent_alias_id</code> = <strong>89</strong>.</li>
</ul></li>
<li><p><strong>Filter Dyads by Models</strong>:</p>
<ul>
<li>From <code>dyad_model.csv</code>, get <code>dyad_id</code>s where <code>model_id</code> is <strong>1</strong> or <strong>5</strong>.</li>
</ul></li>
<li><p><strong>Get Dyads for Dataset</strong>:</p>
<ul>
<li>From <code>dyad.csv</code>, select rows where:
<ul>
<li><code>alias_id</code> is in the list from step 2, and</li>
<li><code>id</code> (dyad_id) is in the list from step 3.</li>
</ul></li>
</ul></li>
<li><p><strong>Retrieve Publications</strong>:</p>
<ul>
<li>Use <code>publication_id</code>s from the filtered dyads to get detailed information from <code>publication.csv</code>.</li>
</ul></li>
</ol>
</section>
<section id="sample-data-illustration-1" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="sample-data-illustration-1"><span class="header-section-number">12</span> Sample Data Illustration</h2>
<p><strong>From <code>dataset_alias.csv</code></strong>:</p>
<!--\~~~markdown-->
<table class="caption-top table">
<thead>
<tr class="header">
<th>alias_id</th>
<th>parent_alias_id</th>
<th>alias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>87</td>
<td>89</td>
<td>Census of Agriculture</td>
</tr>
<tr class="even">
<td>88</td>
<td>89</td>
<td>USDA Census of Agriculture</td>
</tr>
</tbody>
</table>
<p><strong>From <code>dyad.csv</code></strong>:</p>
<!--\~~~markdown-->
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>publication_id</th>
<th>alias_id</th>
<th>mention_candidate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2569</td>
<td>1211491</td>
<td>87</td>
<td>census of agriculture</td>
</tr>
<tr class="even">
<td>2573</td>
<td>1199598</td>
<td>88</td>
<td>usda census of agriculture</td>
</tr>
</tbody>
</table>
<p><strong>From <code>dyad_model.csv</code></strong> (filtered for <code>model_id</code> 1 or 5):</p>
<!--\~~~markdown-->
<table class="caption-top table">
<thead>
<tr class="header">
<th>dyad_id</th>
<th>model_id</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2569</td>
<td>1</td>
</tr>
<tr class="even">
<td>2573</td>
<td>5</td>
</tr>
</tbody>
</table>
<p><strong>Resulting Publications</strong>:</p>
<ul>
<li>Publications with <code>id</code> <strong>1211491</strong> and <strong>1199598</strong> from <code>publication.csv</code>.</li>
</ul>
</section>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<p>This section describes the process of construction CSV files extracted from a SQL Server database. These files contain interconnected data about publications and datasets, specifically focusing on how datasets are mentioned within publications. The main goal is to enable you to analyze the relationships between publications and datasets, particularly those identified using specific search models.</p>
<section id="contents-of-the-csv-files-2" class="level2" data-number="13">
<h2 data-number="13" class="anchored" data-anchor-id="contents-of-the-csv-files-2"><span class="header-section-number">13</span> Contents of the CSV Files</h2>
<p>Below is a detailed explanation of each CSV file and how they relate to one another:</p>
<section id="publication.csv-2" class="level3" data-number="13.1">
<h3 data-number="13.1" class="anchored" data-anchor-id="publication.csv-2"><span class="header-section-number">13.1</span> <strong>publication.csv</strong></h3>
<ul>
<li><strong>Description</strong>: This file contains information about publications, which are the central entities in this dataset.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>id</code>: Unique identifier for each publication.</li>
<li><code>title</code>: Title of the publication.</li>
<li><code>doi</code>: Digital Object Identifier of the publication.</li>
<li><code>year</code> and <code>month</code>: Publication date.</li>
<li>Other metadata such as <code>citation_count</code>, <code>pub_type</code>, etc.</li>
</ul></li>
</ul>
<p><strong>Sample Data</strong>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 59%">
<col style="width: 22%">
<col style="width: 5%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th>id</th>
<th>title</th>
<th>doi</th>
<th>year</th>
<th>month</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>321613</td>
<td>New estimates for CRNA vacancies</td>
<td></td>
<td>2009</td>
<td>4</td>
</tr>
<tr class="even">
<td>321614</td>
<td>Crossing county lines: The impact of crash location and driver’s…</td>
<td>10.1016/j.aap.2006…</td>
<td>2006</td>
<td>7</td>
</tr>
</tbody>
</table>
</section>
<section id="dataset_alias.csv-2" class="level3" data-number="13.2">
<h3 data-number="13.2" class="anchored" data-anchor-id="dataset_alias.csv-2"><span class="header-section-number">13.2</span> <strong>dataset_alias.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Contains all the aliases (alternative names) of datasets. This helps in identifying datasets that might be referred to by different names in publications.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>alias_id</code>: Unique identifier for each alias.</li>
<li><code>parent_alias_id</code>: Identifies the main alias for a dataset. If <code>parent_alias_id</code> equals <code>alias_id</code>, it is the primary alias.</li>
<li><code>alias</code>: The alias name of the dataset.</li>
</ul></li>
</ul>
<p><strong>How to Use</strong>:</p>
<ul>
<li>To find the main alias of a dataset, look for rows where <code>alias_id</code> equals <code>parent_alias_id</code>.</li>
<li>To find all aliases of a dataset, filter by <code>parent_alias_id</code> corresponding to the main alias.</li>
</ul>
<p><strong>Sample Data</strong>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 20%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>id</th>
<th>alias_id</th>
<th>parent_alias_id</th>
<th>alias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1676</td>
<td>87</td>
<td>89</td>
<td>Census of Agriculture</td>
</tr>
<tr class="even">
<td>1673</td>
<td>12</td>
<td>282</td>
<td>ARMS Farm Financial and Crop Production Practices</td>
</tr>
</tbody>
</table>
</section>
<section id="dyad.csv-2" class="level3" data-number="13.3">
<h3 data-number="13.3" class="anchored" data-anchor-id="dyad.csv-2"><span class="header-section-number">13.3</span> <strong>dyad.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Represents the mentions of dataset aliases found within publications. Acts as a linking table between <code>publication.csv</code> and <code>dataset_alias.csv</code>.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>id</code>: Unique identifier for each dyad (mention).</li>
<li><code>publication_id</code>: References the <code>id</code> in <code>publication.csv</code>.</li>
<li><code>alias_id</code>: References the <code>alias_id</code> in <code>dataset_alias.csv</code>.</li>
<li><code>mention_candidate</code>: The actual text mentioning the dataset in the publication.</li>
</ul></li>
</ul>
<p><strong>Sample Data</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>publication_id</th>
<th>alias_id</th>
<th>mention_candidate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2569</td>
<td>1211491</td>
<td>87</td>
<td>census of agriculture</td>
</tr>
<tr class="even">
<td>2573</td>
<td>1199598</td>
<td>88</td>
<td>usda census of agriculture</td>
</tr>
</tbody>
</table>
</section>
<section id="model.csv-2" class="level3" data-number="13.4">
<h3 data-number="13.4" class="anchored" data-anchor-id="model.csv-2"><span class="header-section-number">13.4</span> <strong>model.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Lists the different models or methods used to identify dataset mentions within publications.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>id</code>: Unique identifier for each model.</li>
<li><code>name</code>: Name of the model (e.g., <code>string_matching</code>, <code>refmatch</code>).</li>
</ul></li>
</ul>
<p><strong>Relevant Models</strong>:</p>
<ul>
<li><strong>Model ID 1</strong>: <code>string_matching</code></li>
<li><strong>Model ID 5</strong>: <code>refmatch</code></li>
</ul>
<p>These are the models we are focusing on to compare with data extracted from OpenAlex, as no Kaggle model has been applied there.</p>
<p><strong>Sample Data</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>string_matching</td>
</tr>
<tr class="even">
<td>5</td>
<td>refmatch</td>
</tr>
</tbody>
</table>
</section>
<section id="dyad_model.csv-2" class="level3" data-number="13.5">
<h3 data-number="13.5" class="anchored" data-anchor-id="dyad_model.csv-2"><span class="header-section-number">13.5</span> <strong>dyad_model.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Connects dyads with the models that identified them. Allows filtering dyads based on the models used.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>dyad_id</code>: References the <code>id</code> in <code>dyad.csv</code>.</li>
<li><code>model_id</code>: References the <code>id</code> in <code>model.csv</code>.</li>
</ul></li>
</ul>
<p><strong>How to Use</strong>:</p>
<ul>
<li>To filter dyads (and thus publications) identified by specific models, perform an inner join with <code>dyad.csv</code> on <code>dyad_id</code> and filter by <code>model_id</code>.</li>
</ul>
<p><strong>Sample Data</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>dyad_id</th>
<th>model_id</th>
<th>score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4928</td>
<td>2569</td>
<td>1</td>
<td>2.0</td>
</tr>
<tr class="even">
<td>4929</td>
<td>2569</td>
<td>4</td>
<td>1.0</td>
</tr>
<tr class="odd">
<td>4930</td>
<td>2569</td>
<td>2</td>
<td>1.0</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="how-to-extract-publications-for-a-specific-dataset-2" class="level2" data-number="14">
<h2 data-number="14" class="anchored" data-anchor-id="how-to-extract-publications-for-a-specific-dataset-2"><span class="header-section-number">14</span> How to Extract Publications for a Specific Dataset</h2>
<p>To find all publications associated with a particular dataset, such as the <strong>NASS Census of Agriculture</strong>, follow these steps:</p>
<ol type="1">
<li><p><strong>Identify the Main Alias</strong>:</p>
<ul>
<li>Find the <code>alias_id</code> where <code>alias_id</code> equals <code>parent_alias_id</code> for the dataset.</li>
<li>For <strong>NASS Census of Agriculture</strong>, the main alias has <code>alias_id</code> = <strong>89</strong>.</li>
</ul></li>
<li><p><strong>Get All Aliases</strong>:</p>
<ul>
<li>In <code>dataset_alias.csv</code>, filter rows where <code>parent_alias_id</code> equals <strong>89</strong>.</li>
<li>This gives you all aliases associated with the <strong>NASS Census of Agriculture</strong> dataset.</li>
</ul></li>
<li><p><strong>Link Aliases to Publications</strong>:</p>
<ul>
<li>In <code>dyad.csv</code>, filter rows where <code>alias_id</code> matches any of the <code>alias_id</code>s obtained in step 2.</li>
<li>This will give you <code>publication_id</code>s of publications mentioning any alias of the dataset.</li>
</ul></li>
<li><p><strong>Retrieve Publication Details</strong>:</p>
<ul>
<li>Using the <code>publication_id</code>s from step 3, retrieve the corresponding records from <code>publication.csv</code>.</li>
</ul></li>
</ol>
</section>
<section id="filtering-publications-by-specific-models-2" class="level2" data-number="15">
<h2 data-number="15" class="anchored" data-anchor-id="filtering-publications-by-specific-models-2"><span class="header-section-number">15</span> Filtering Publications by Specific Models</h2>
<p>Since we’re interested in mentions identified by the <strong><code>string_matching</code></strong> and <strong><code>refmatch</code></strong> models (models with <code>id</code> 1 and 5), follow these steps:</p>
<ol type="1">
<li><p><strong>Filter Dyads by Model</strong>:</p>
<ul>
<li>In <code>dyad_model.csv</code>, filter rows where <code>model_id</code> is <strong>1</strong> or <strong>5</strong>.</li>
<li>This gives you <code>dyad_id</code>s linked to these models.</li>
</ul></li>
<li><p><strong>Get Relevant Dyads</strong>:</p>
<ul>
<li>Perform an inner join with <code>dyad.csv</code> on <code>dyad_id</code>.</li>
<li>This filters dyads to only those identified by the specified models.</li>
</ul></li>
<li><p><strong>Proceed as Before</strong>:</p>
<ul>
<li>Continue with the steps in the previous section, but using the filtered dyads from step 2.</li>
</ul></li>
</ol>
</section>
<section id="practical-example-2" class="level2" data-number="16">
<h2 data-number="16" class="anchored" data-anchor-id="practical-example-2"><span class="header-section-number">16</span> Practical Example</h2>
<p><strong>Objective</strong>: Find all publications mentioning the <strong>NASS Census of Agriculture</strong> dataset using the <code>string_matching</code> and <code>refmatch</code> models.</p>
<p><strong>Steps</strong>:</p>
<ol type="1">
<li><p><strong>Find Main Alias ID</strong>:</p>
<ul>
<li>Main alias <code>alias_id</code> = <strong>89</strong>.</li>
</ul></li>
<li><p><strong>Get All Aliases</strong>:</p>
<ul>
<li>From <code>dataset_alias.csv</code>, extract all <code>alias_id</code>s where <code>parent_alias_id</code> = <strong>89</strong>.</li>
</ul></li>
<li><p><strong>Filter Dyads by Models</strong>:</p>
<ul>
<li>From <code>dyad_model.csv</code>, get <code>dyad_id</code>s where <code>model_id</code> is <strong>1</strong> or <strong>5</strong>.</li>
</ul></li>
<li><p><strong>Get Dyads for Dataset</strong>:</p>
<ul>
<li>From <code>dyad.csv</code>, select rows where:
<ul>
<li><code>alias_id</code> is in the list from step 2, and</li>
<li><code>id</code> (dyad_id) is in the list from step 3.</li>
</ul></li>
</ul></li>
<li><p><strong>Retrieve Publications</strong>:</p>
<ul>
<li>Use <code>publication_id</code>s from the filtered dyads to get detailed information from <code>publication.csv</code>.</li>
</ul></li>
</ol>
</section>
<section id="sample-data-illustration-2" class="level2" data-number="17">
<h2 data-number="17" class="anchored" data-anchor-id="sample-data-illustration-2"><span class="header-section-number">17</span> Sample Data Illustration</h2>
<p><strong>From <code>dataset_alias.csv</code></strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>alias_id</th>
<th>parent_alias_id</th>
<th>alias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>87</td>
<td>89</td>
<td>Census of Agriculture</td>
</tr>
<tr class="even">
<td>88</td>
<td>89</td>
<td>USDA Census of Agriculture</td>
</tr>
</tbody>
</table>
<p><strong>From <code>dyad.csv</code></strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>publication_id</th>
<th>alias_id</th>
<th>mention_candidate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2569</td>
<td>1211491</td>
<td>87</td>
<td>census of agriculture</td>
</tr>
<tr class="even">
<td>2573</td>
<td>1199598</td>
<td>88</td>
<td>usda census of agriculture</td>
</tr>
</tbody>
</table>
<p><strong>From <code>dyad_model.csv</code></strong> (filtered for <code>model_id</code> 1 or 5):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>dyad_id</th>
<th>model_id</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2569</td>
<td>1</td>
</tr>
<tr class="even">
<td>2573</td>
<td>5</td>
</tr>
</tbody>
</table>
<p><strong>Resulting Publications</strong>:</p>
<ul>
<li>Publications with <code>id</code> <strong>1211491</strong> and <strong>1199598</strong> from <code>publication.csv</code>.</li>
</ul>
</section>
<section id="conclusion-1" class="level2" data-number="18">
<h2 data-number="18" class="anchored" data-anchor-id="conclusion-1"><span class="header-section-number">18</span> Conclusion</h2>
<p>By following the steps outlined above, you can effectively navigate the dataset to extract publications related to specific datasets and identified by particular models. This structured approach allows for targeted analysis and comparison with data from sources like OpenAlex.</p>
</section>
</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<p>This section describes the process of construction CSV files extracted from a SQL Server database. These files contain interconnected data about publications and datasets, specifically focusing on how datasets are mentioned within publications. The main goal is to enable you to analyze the relationships between publications and datasets, particularly those identified using specific search models.</p>
<p>Unlike the initial dataset from Scopus, the OpenAlex publications can be associated with multiple datasets. Two new files are introduced:</p>
<ul>
<li><strong>dataset.csv</strong>: Lists all datasets identified in OpenAlex. This contains details of all USDA datasets.</li>
<li><strong>publication_dataset_links.csv</strong>: Connects publications with one or more datasets in the OpenAlex data. Indicates which publications are associated with which datasets.</li>
</ul>
<p>The search in OpenAlex was performed using the same aliases and flag terms applied in the Scopus data, without any optimization. As a consequence, the “NASS Census of Agriculture” dataset currently shows fewer publications than in the previous sample due to this direct, unoptimized search approach.</p>
<section id="contents-of-the-csv-files-3" class="level2" data-number="19">
<h2 data-number="19" class="anchored" data-anchor-id="contents-of-the-csv-files-3"><span class="header-section-number">19</span> Contents of the CSV Files</h2>
<p>Below is a detailed explanation of the SQL Server-related CSV files and how they relate to one another:</p>
<section id="publication.csv-3" class="level3" data-number="19.1">
<h3 data-number="19.1" class="anchored" data-anchor-id="publication.csv-3"><span class="header-section-number">19.1</span> <strong>publication.csv</strong></h3>
<ul>
<li><strong>Description</strong>: This file contains information about publications, which are the central entities in this dataset.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>id</code>: Unique identifier for each publication.</li>
<li><code>title</code>: Title of the publication.</li>
<li><code>doi</code>: Digital Object Identifier of the publication.</li>
<li><code>year</code> and <code>month</code>: Publication date.</li>
<li>Other metadata such as <code>citation_count</code>, <code>pub_type</code>, etc.</li>
</ul></li>
</ul>
<p><strong>Sample Data</strong>:</p>
<!--\~~~markdown-->
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 59%">
<col style="width: 22%">
<col style="width: 5%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th>id</th>
<th>title</th>
<th>doi</th>
<th>year</th>
<th>month</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>321613</td>
<td>New estimates for CRNA vacancies</td>
<td></td>
<td>2009</td>
<td>4</td>
</tr>
<tr class="even">
<td>321614</td>
<td>Crossing county lines: The impact of crash location and driver’s…</td>
<td>10.1016/j.aap.2006…</td>
<td>2006</td>
<td>7</td>
</tr>
</tbody>
</table>
</section>
<section id="dataset_alias.csv-3" class="level3" data-number="19.2">
<h3 data-number="19.2" class="anchored" data-anchor-id="dataset_alias.csv-3"><span class="header-section-number">19.2</span> <strong>dataset_alias.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Contains all the aliases (alternative names) of datasets. This helps in identifying datasets that might be referred to by different names in publications.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>alias_id</code>: Unique identifier for each alias.</li>
<li><code>parent_alias_id</code>: Identifies the main alias for a dataset. If <code>parent_alias_id</code> equals <code>alias_id</code>, it is the primary alias.</li>
<li><code>alias</code>: The alias name of the dataset.</li>
</ul></li>
</ul>
<p><strong>How to Use</strong>:</p>
<ul>
<li>To find the main alias of a dataset, look for rows where <code>alias_id</code> equals <code>parent_alias_id</code>.</li>
<li>To find all aliases of a dataset, filter by <code>parent_alias_id</code> corresponding to the main alias.</li>
</ul>
<p><strong>Sample Data</strong>:</p>
<!--\~~~markdown-->
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 20%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>id</th>
<th>alias_id</th>
<th>parent_alias_id</th>
<th>alias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1676</td>
<td>87</td>
<td>89</td>
<td>Census of Agriculture</td>
</tr>
<tr class="even">
<td>1673</td>
<td>12</td>
<td>282</td>
<td>ARMS Farm Financial and Crop Production Practices</td>
</tr>
</tbody>
</table>
</section>
<section id="dyad.csv-3" class="level3" data-number="19.3">
<h3 data-number="19.3" class="anchored" data-anchor-id="dyad.csv-3"><span class="header-section-number">19.3</span> <strong>dyad.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Represents the mentions of dataset aliases found within publications. Acts as a linking table between <code>publication.csv</code> and <code>dataset_alias.csv</code>.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>id</code>: Unique identifier for each dyad (mention).</li>
<li><code>publication_id</code>: References the <code>id</code> in <code>publication.csv</code>.</li>
<li><code>alias_id</code>: References the <code>alias_id</code> in <code>dataset_alias.csv</code>.</li>
<li><code>mention_candidate</code>: The actual text mentioning the dataset in the publication.</li>
</ul></li>
</ul>
<p><strong>Sample Data</strong>:</p>
<!--\~~~markdown-->
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>publication_id</th>
<th>alias_id</th>
<th>mention_candidate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2569</td>
<td>1211491</td>
<td>87</td>
<td>census of agriculture</td>
</tr>
<tr class="even">
<td>2573</td>
<td>1199598</td>
<td>88</td>
<td>usda census of agriculture</td>
</tr>
</tbody>
</table>
</section>
<section id="model.csv-3" class="level3" data-number="19.4">
<h3 data-number="19.4" class="anchored" data-anchor-id="model.csv-3"><span class="header-section-number">19.4</span> <strong>model.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Lists the different models or methods used to identify dataset mentions within publications.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>id</code>: Unique identifier for each model.</li>
<li><code>name</code>: Name of the model (e.g., <code>string_matching</code>, <code>refmatch</code>).</li>
</ul></li>
</ul>
<p><strong>Relevant Models</strong>:</p>
<ul>
<li><strong>Model ID 1</strong>: <code>string_matching</code></li>
<li><strong>Model ID 5</strong>: <code>refmatch</code></li>
</ul>
<p>These are the models we are focusing on to compare with data extracted from OpenAlex, as no Kaggle model has been applied there.</p>
<p><strong>Sample Data</strong>:</p>
<!--\~~~markdown-->
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>string_matching</td>
</tr>
<tr class="even">
<td>5</td>
<td>refmatch</td>
</tr>
</tbody>
</table>
</section>
<section id="dyad_model.csv-3" class="level3" data-number="19.5">
<h3 data-number="19.5" class="anchored" data-anchor-id="dyad_model.csv-3"><span class="header-section-number">19.5</span> <strong>dyad_model.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Connects dyads with the models that identified them. Allows filtering dyads based on the models used.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>dyad_id</code>: References the <code>id</code> in <code>dyad.csv</code>.</li>
<li><code>model_id</code>: References the <code>id</code> in <code>model.csv</code>.</li>
</ul></li>
</ul>
<p><strong>How to Use</strong>:</p>
<ul>
<li>To filter dyads (and thus publications) identified by specific models, perform an inner join with <code>dyad.csv</code> on <code>dyad_id</code> and filter by <code>model_id</code>.</li>
</ul>
<p><strong>Sample Data</strong>:</p>
<!--\~~~markdown-->
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>dyad_id</th>
<th>model_id</th>
<th>score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4928</td>
<td>2569</td>
<td>1</td>
<td>2.0</td>
</tr>
<tr class="even">
<td>4929</td>
<td>2569</td>
<td>4</td>
<td>1.0</td>
</tr>
<tr class="odd">
<td>4930</td>
<td>2569</td>
<td>2</td>
<td>1.0</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="how-the-files-are-related-1" class="level2" data-number="20">
<h2 data-number="20" class="anchored" data-anchor-id="how-the-files-are-related-1"><span class="header-section-number">20</span> How the Files are Related</h2>
<p>The files are structured to represent entities (publications, journals, institutions, authors) and their relationships. The main publication data is in <code>publications_main.csv</code>, and the details about journals, institutions, and authors are in their respective files. The link files (<code>publication_journal_links.csv</code>, <code>publication_institution_links.csv</code>, <code>publication_author_links.csv</code>) represent the many-to-many relationships between publications and these entities.</p>
<p>By using the OpenAlex identifiers, you can join these files to perform comprehensive analyses. For example:</p>
<ul>
<li>To find all publications by a specific author, you can use <code>authors.csv</code> to find the author’s <code>author_openalex_id</code> and then use <code>publication_author_links.csv</code> to find the associated publications.</li>
<li>To analyze the distribution of publications across journals, you can join <code>publications_main.csv</code>, <code>publication_journal_links.csv</code>, and <code>journals.csv</code> on <code>publication_openalex_id</code> and <code>journal_openalex_id</code>.</li>
</ul>
</section>
<section id="how-to-extract-publications-for-a-specific-dataset-3" class="level2" data-number="21">
<h2 data-number="21" class="anchored" data-anchor-id="how-to-extract-publications-for-a-specific-dataset-3"><span class="header-section-number">21</span> How to Extract Publications for a Specific Dataset</h2>
<p>To find all publications associated with a particular dataset, such as the <strong>NASS Census of Agriculture</strong>, follow these steps:</p>
<ol type="1">
<li><p><strong>Identify the Main Alias</strong>:</p>
<ul>
<li>Find the <code>alias_id</code> where <code>alias_id</code> equals <code>parent_alias_id</code> for the dataset.</li>
<li>For <strong>NASS Census of Agriculture</strong>, the main alias has <code>alias_id</code> = <strong>89</strong>.</li>
</ul></li>
<li><p><strong>Get All Aliases</strong>:</p>
<ul>
<li>In <code>dataset_alias.csv</code>, filter rows where <code>parent_alias_id</code> equals <strong>89</strong>.</li>
<li>This gives you all aliases associated with the <strong>NASS Census of Agriculture</strong> dataset.</li>
</ul></li>
<li><p><strong>Link Aliases to Publications</strong>:</p>
<ul>
<li>In <code>dyad.csv</code>, filter rows where <code>alias_id</code> matches any of the <code>alias_id</code>s obtained in step 2.</li>
<li>This will give you <code>publication_id</code>s of publications mentioning any alias of the dataset.</li>
</ul></li>
<li><p><strong>Retrieve Publication Details</strong>:</p>
<ul>
<li>Using the <code>publication_id</code>s from step 3, retrieve the corresponding records from <code>publication.csv</code>.</li>
</ul></li>
</ol>
</section>
<section id="filtering-publications-by-specific-models-3" class="level2" data-number="22">
<h2 data-number="22" class="anchored" data-anchor-id="filtering-publications-by-specific-models-3"><span class="header-section-number">22</span> Filtering Publications by Specific Models</h2>
<p>Since we’re interested in mentions identified by the <strong><code>string_matching</code></strong> and <strong><code>refmatch</code></strong> models (models with <code>id</code> 1 and 5), follow these steps:</p>
<ol type="1">
<li><p><strong>Filter Dyads by Model</strong>:</p>
<ul>
<li>In <code>dyad_model.csv</code>, filter rows where <code>model_id</code> is <strong>1</strong> or <strong>5</strong>.</li>
<li>This gives you <code>dyad_id</code>s linked to these models.</li>
</ul></li>
<li><p><strong>Get Relevant Dyads</strong>:</p>
<ul>
<li>Perform an inner join with <code>dyad.csv</code> on <code>dyad_id</code>.</li>
<li>This filters dyads to only those identified by the specified models.</li>
</ul></li>
<li><p><strong>Proceed as Before</strong>:</p>
<ul>
<li>Continue with the steps in the previous section, but using the filtered dyads from step 2.</li>
</ul></li>
</ol>
</section>
<section id="practical-example-3" class="level2" data-number="23">
<h2 data-number="23" class="anchored" data-anchor-id="practical-example-3"><span class="header-section-number">23</span> Practical Example</h2>
<p><strong>Objective</strong>: Find all publications mentioning the <strong>NASS Census of Agriculture</strong> dataset using the <code>string_matching</code> and <code>refmatch</code> models.</p>
<p><strong>Steps</strong>:</p>
<ol type="1">
<li><p><strong>Find Main Alias ID</strong>:</p>
<ul>
<li>Main alias <code>alias_id</code> = <strong>89</strong>.</li>
</ul></li>
<li><p><strong>Get All Aliases</strong>:</p>
<ul>
<li>From <code>dataset_alias.csv</code>, extract all <code>alias_id</code>s where <code>parent_alias_id</code> = <strong>89</strong>.</li>
</ul></li>
<li><p><strong>Filter Dyads by Models</strong>:</p>
<ul>
<li>From <code>dyad_model.csv</code>, get <code>dyad_id</code>s where <code>model_id</code> is <strong>1</strong> or <strong>5</strong>.</li>
</ul></li>
<li><p><strong>Get Dyads for Dataset</strong>:</p>
<ul>
<li>From <code>dyad.csv</code>, select rows where:
<ul>
<li><code>alias_id</code> is in the list from step 2, and</li>
<li><code>id</code> (dyad_id) is in the list from step 3.</li>
</ul></li>
</ul></li>
<li><p><strong>Retrieve Publications</strong>:</p>
<ul>
<li>Use <code>publication_id</code>s from the filtered dyads to get detailed information from <code>publication.csv</code>.</li>
</ul></li>
</ol>
</section>
<section id="sample-data-illustration-3" class="level2" data-number="24">
<h2 data-number="24" class="anchored" data-anchor-id="sample-data-illustration-3"><span class="header-section-number">24</span> Sample Data Illustration</h2>
<p><strong>From <code>dataset_alias.csv</code></strong>:</p>
<!--\~~~markdown-->
<table class="caption-top table">
<thead>
<tr class="header">
<th>alias_id</th>
<th>parent_alias_id</th>
<th>alias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>87</td>
<td>89</td>
<td>Census of Agriculture</td>
</tr>
<tr class="even">
<td>88</td>
<td>89</td>
<td>USDA Census of Agriculture</td>
</tr>
</tbody>
</table>
<p><strong>From <code>dyad.csv</code></strong>:</p>
<!--\~~~markdown-->
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>publication_id</th>
<th>alias_id</th>
<th>mention_candidate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2569</td>
<td>1211491</td>
<td>87</td>
<td>census of agriculture</td>
</tr>
<tr class="even">
<td>2573</td>
<td>1199598</td>
<td>88</td>
<td>usda census of agriculture</td>
</tr>
</tbody>
</table>
<p><strong>From <code>dyad_model.csv</code></strong> (filtered for <code>model_id</code> 1 or 5):</p>
<!--\~~~markdown-->
<table class="caption-top table">
<thead>
<tr class="header">
<th>dyad_id</th>
<th>model_id</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2569</td>
<td>1</td>
</tr>
<tr class="even">
<td>2573</td>
<td>5</td>
</tr>
</tbody>
</table>
<p><strong>Resulting Publications</strong>:</p>
<ul>
<li>Publications with <code>id</code> <strong>1211491</strong> and <strong>1199598</strong> from <code>publication.csv</code>.</li>
</ul>
</section>
</div>
<div id="tabset-1-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-5-tab">
<p>This section describes the process of construction CSV files extracted from a SQL Server database. These files contain interconnected data about publications and datasets, specifically focusing on how datasets are mentioned within publications. The main goal is to enable you to analyze the relationships between publications and datasets, particularly those identified using specific search models.</p>
<section id="contents-of-the-csv-files-4" class="level2" data-number="25">
<h2 data-number="25" class="anchored" data-anchor-id="contents-of-the-csv-files-4"><span class="header-section-number">25</span> Contents of the CSV Files</h2>
<p>Below is a detailed explanation of each CSV file and how they relate to one another:</p>
<section id="publication.csv-4" class="level3" data-number="25.1">
<h3 data-number="25.1" class="anchored" data-anchor-id="publication.csv-4"><span class="header-section-number">25.1</span> <strong>publication.csv</strong></h3>
<ul>
<li><strong>Description</strong>: This file contains information about publications, which are the central entities in this dataset.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>id</code>: Unique identifier for each publication.</li>
<li><code>title</code>: Title of the publication.</li>
<li><code>doi</code>: Digital Object Identifier of the publication.</li>
<li><code>year</code> and <code>month</code>: Publication date.</li>
<li>Other metadata such as <code>citation_count</code>, <code>pub_type</code>, etc.</li>
</ul></li>
</ul>
<p><strong>Sample Data</strong>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 59%">
<col style="width: 22%">
<col style="width: 5%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th>id</th>
<th>title</th>
<th>doi</th>
<th>year</th>
<th>month</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>321613</td>
<td>New estimates for CRNA vacancies</td>
<td></td>
<td>2009</td>
<td>4</td>
</tr>
<tr class="even">
<td>321614</td>
<td>Crossing county lines: The impact of crash location and driver’s…</td>
<td>10.1016/j.aap.2006…</td>
<td>2006</td>
<td>7</td>
</tr>
</tbody>
</table>
</section>
<section id="dataset_alias.csv-4" class="level3" data-number="25.2">
<h3 data-number="25.2" class="anchored" data-anchor-id="dataset_alias.csv-4"><span class="header-section-number">25.2</span> <strong>dataset_alias.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Contains all the aliases (alternative names) of datasets. This helps in identifying datasets that might be referred to by different names in publications.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>alias_id</code>: Unique identifier for each alias.</li>
<li><code>parent_alias_id</code>: Identifies the main alias for a dataset. If <code>parent_alias_id</code> equals <code>alias_id</code>, it is the primary alias.</li>
<li><code>alias</code>: The alias name of the dataset.</li>
</ul></li>
</ul>
<p><strong>How to Use</strong>:</p>
<ul>
<li>To find the main alias of a dataset, look for rows where <code>alias_id</code> equals <code>parent_alias_id</code>.</li>
<li>To find all aliases of a dataset, filter by <code>parent_alias_id</code> corresponding to the main alias.</li>
</ul>
<p><strong>Sample Data</strong>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 20%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>id</th>
<th>alias_id</th>
<th>parent_alias_id</th>
<th>alias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1676</td>
<td>87</td>
<td>89</td>
<td>Census of Agriculture</td>
</tr>
<tr class="even">
<td>1673</td>
<td>12</td>
<td>282</td>
<td>ARMS Farm Financial and Crop Production Practices</td>
</tr>
</tbody>
</table>
</section>
<section id="dyad.csv-4" class="level3" data-number="25.3">
<h3 data-number="25.3" class="anchored" data-anchor-id="dyad.csv-4"><span class="header-section-number">25.3</span> <strong>dyad.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Represents the mentions of dataset aliases found within publications. Acts as a linking table between <code>publication.csv</code> and <code>dataset_alias.csv</code>.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>id</code>: Unique identifier for each dyad (mention).</li>
<li><code>publication_id</code>: References the <code>id</code> in <code>publication.csv</code>.</li>
<li><code>alias_id</code>: References the <code>alias_id</code> in <code>dataset_alias.csv</code>.</li>
<li><code>mention_candidate</code>: The actual text mentioning the dataset in the publication.</li>
</ul></li>
</ul>
<p><strong>Sample Data</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>publication_id</th>
<th>alias_id</th>
<th>mention_candidate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2569</td>
<td>1211491</td>
<td>87</td>
<td>census of agriculture</td>
</tr>
<tr class="even">
<td>2573</td>
<td>1199598</td>
<td>88</td>
<td>usda census of agriculture</td>
</tr>
</tbody>
</table>
</section>
<section id="model.csv-4" class="level3" data-number="25.4">
<h3 data-number="25.4" class="anchored" data-anchor-id="model.csv-4"><span class="header-section-number">25.4</span> <strong>model.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Lists the different models or methods used to identify dataset mentions within publications.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>id</code>: Unique identifier for each model.</li>
<li><code>name</code>: Name of the model (e.g., <code>string_matching</code>, <code>refmatch</code>).</li>
</ul></li>
</ul>
<p><strong>Relevant Models</strong>:</p>
<ul>
<li><strong>Model ID 1</strong>: <code>string_matching</code></li>
<li><strong>Model ID 5</strong>: <code>refmatch</code></li>
</ul>
<p>These are the models we are focusing on to compare with data extracted from OpenAlex, as no Kaggle model has been applied there.</p>
<p><strong>Sample Data</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>string_matching</td>
</tr>
<tr class="even">
<td>5</td>
<td>refmatch</td>
</tr>
</tbody>
</table>
</section>
<section id="dyad_model.csv-4" class="level3" data-number="25.5">
<h3 data-number="25.5" class="anchored" data-anchor-id="dyad_model.csv-4"><span class="header-section-number">25.5</span> <strong>dyad_model.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Connects dyads with the models that identified them. Allows filtering dyads based on the models used.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>dyad_id</code>: References the <code>id</code> in <code>dyad.csv</code>.</li>
<li><code>model_id</code>: References the <code>id</code> in <code>model.csv</code>.</li>
</ul></li>
</ul>
<p><strong>How to Use</strong>:</p>
<ul>
<li>To filter dyads (and thus publications) identified by specific models, perform an inner join with <code>dyad.csv</code> on <code>dyad_id</code> and filter by <code>model_id</code>.</li>
</ul>
<p><strong>Sample Data</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>dyad_id</th>
<th>model_id</th>
<th>score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4928</td>
<td>2569</td>
<td>1</td>
<td>2.0</td>
</tr>
<tr class="even">
<td>4929</td>
<td>2569</td>
<td>4</td>
<td>1.0</td>
</tr>
<tr class="odd">
<td>4930</td>
<td>2569</td>
<td>2</td>
<td>1.0</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="how-to-extract-publications-for-a-specific-dataset-4" class="level2" data-number="26">
<h2 data-number="26" class="anchored" data-anchor-id="how-to-extract-publications-for-a-specific-dataset-4"><span class="header-section-number">26</span> How to Extract Publications for a Specific Dataset</h2>
<p>To find all publications associated with a particular dataset, such as the <strong>NASS Census of Agriculture</strong>, follow these steps:</p>
<ol type="1">
<li><p><strong>Identify the Main Alias</strong>:</p>
<ul>
<li>Find the <code>alias_id</code> where <code>alias_id</code> equals <code>parent_alias_id</code> for the dataset.</li>
<li>For <strong>NASS Census of Agriculture</strong>, the main alias has <code>alias_id</code> = <strong>89</strong>.</li>
</ul></li>
<li><p><strong>Get All Aliases</strong>:</p>
<ul>
<li>In <code>dataset_alias.csv</code>, filter rows where <code>parent_alias_id</code> equals <strong>89</strong>.</li>
<li>This gives you all aliases associated with the <strong>NASS Census of Agriculture</strong> dataset.</li>
</ul></li>
<li><p><strong>Link Aliases to Publications</strong>:</p>
<ul>
<li>In <code>dyad.csv</code>, filter rows where <code>alias_id</code> matches any of the <code>alias_id</code>s obtained in step 2.</li>
<li>This will give you <code>publication_id</code>s of publications mentioning any alias of the dataset.</li>
</ul></li>
<li><p><strong>Retrieve Publication Details</strong>:</p>
<ul>
<li>Using the <code>publication_id</code>s from step 3, retrieve the corresponding records from <code>publication.csv</code>.</li>
</ul></li>
</ol>
</section>
<section id="filtering-publications-by-specific-models-4" class="level2" data-number="27">
<h2 data-number="27" class="anchored" data-anchor-id="filtering-publications-by-specific-models-4"><span class="header-section-number">27</span> Filtering Publications by Specific Models</h2>
<p>Since we’re interested in mentions identified by the <strong><code>string_matching</code></strong> and <strong><code>refmatch</code></strong> models (models with <code>id</code> 1 and 5), follow these steps:</p>
<ol type="1">
<li><p><strong>Filter Dyads by Model</strong>:</p>
<ul>
<li>In <code>dyad_model.csv</code>, filter rows where <code>model_id</code> is <strong>1</strong> or <strong>5</strong>.</li>
<li>This gives you <code>dyad_id</code>s linked to these models.</li>
</ul></li>
<li><p><strong>Get Relevant Dyads</strong>:</p>
<ul>
<li>Perform an inner join with <code>dyad.csv</code> on <code>dyad_id</code>.</li>
<li>This filters dyads to only those identified by the specified models.</li>
</ul></li>
<li><p><strong>Proceed as Before</strong>:</p>
<ul>
<li>Continue with the steps in the previous section, but using the filtered dyads from step 2.</li>
</ul></li>
</ol>
</section>
<section id="practical-example-4" class="level2" data-number="28">
<h2 data-number="28" class="anchored" data-anchor-id="practical-example-4"><span class="header-section-number">28</span> Practical Example</h2>
<p><strong>Objective</strong>: Find all publications mentioning the <strong>NASS Census of Agriculture</strong> dataset using the <code>string_matching</code> and <code>refmatch</code> models.</p>
<p><strong>Steps</strong>:</p>
<ol type="1">
<li><p><strong>Find Main Alias ID</strong>:</p>
<ul>
<li>Main alias <code>alias_id</code> = <strong>89</strong>.</li>
</ul></li>
<li><p><strong>Get All Aliases</strong>:</p>
<ul>
<li>From <code>dataset_alias.csv</code>, extract all <code>alias_id</code>s where <code>parent_alias_id</code> = <strong>89</strong>.</li>
</ul></li>
<li><p><strong>Filter Dyads by Models</strong>:</p>
<ul>
<li>From <code>dyad_model.csv</code>, get <code>dyad_id</code>s where <code>model_id</code> is <strong>1</strong> or <strong>5</strong>.</li>
</ul></li>
<li><p><strong>Get Dyads for Dataset</strong>:</p>
<ul>
<li>From <code>dyad.csv</code>, select rows where:
<ul>
<li><code>alias_id</code> is in the list from step 2, and</li>
<li><code>id</code> (dyad_id) is in the list from step 3.</li>
</ul></li>
</ul></li>
<li><p><strong>Retrieve Publications</strong>:</p>
<ul>
<li>Use <code>publication_id</code>s from the filtered dyads to get detailed information from <code>publication.csv</code>.</li>
</ul></li>
</ol>
</section>
<section id="sample-data-illustration-4" class="level2" data-number="29">
<h2 data-number="29" class="anchored" data-anchor-id="sample-data-illustration-4"><span class="header-section-number">29</span> Sample Data Illustration</h2>
<p><strong>From <code>dataset_alias.csv</code></strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>alias_id</th>
<th>parent_alias_id</th>
<th>alias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>87</td>
<td>89</td>
<td>Census of Agriculture</td>
</tr>
<tr class="even">
<td>88</td>
<td>89</td>
<td>USDA Census of Agriculture</td>
</tr>
</tbody>
</table>
<p><strong>From <code>dyad.csv</code></strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>publication_id</th>
<th>alias_id</th>
<th>mention_candidate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2569</td>
<td>1211491</td>
<td>87</td>
<td>census of agriculture</td>
</tr>
<tr class="even">
<td>2573</td>
<td>1199598</td>
<td>88</td>
<td>usda census of agriculture</td>
</tr>
</tbody>
</table>
<p><strong>From <code>dyad_model.csv</code></strong> (filtered for <code>model_id</code> 1 or 5):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>dyad_id</th>
<th>model_id</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2569</td>
<td>1</td>
</tr>
<tr class="even">
<td>2573</td>
<td>5</td>
</tr>
</tbody>
</table>
<p><strong>Resulting Publications</strong>:</p>
<ul>
<li>Publications with <code>id</code> <strong>1211491</strong> and <strong>1199598</strong> from <code>publication.csv</code>.</li>
</ul>
</section>
<section id="conclusion-2" class="level2" data-number="30">
<h2 data-number="30" class="anchored" data-anchor-id="conclusion-2"><span class="header-section-number">30</span> Conclusion</h2>
<p>By following the steps outlined above, you can effectively navigate the dataset to extract publications related to specific datasets and identified by particular models. This structured approach allows for targeted analysis and comparison with data from sources like OpenAlex.</p>
</section>
</div>
<div id="tabset-1-6" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-6-tab">
<p>This section describes the process of construction CSV files extracted from a SQL Server database. These files contain interconnected data about publications and datasets, specifically focusing on how datasets are mentioned within publications. The main goal is to enable you to analyze the relationships between publications and datasets, particularly those identified using specific search models.</p>
<p>Unlike the initial dataset from Scopus, the OpenAlex publications can be associated with multiple datasets. Two new files are introduced:</p>
<ul>
<li><strong>dataset.csv</strong>: Lists all datasets identified in OpenAlex. This contains details of all USDA datasets.</li>
<li><strong>publication_dataset_links.csv</strong>: Connects publications with one or more datasets in the OpenAlex data. Indicates which publications are associated with which datasets.</li>
</ul>
<p>The search in OpenAlex was performed using the same aliases and flag terms applied in the Scopus data, without any optimization. As a consequence, the “NASS Census of Agriculture” dataset currently shows fewer publications than in the previous sample due to this direct, unoptimized search approach.</p>
<section id="contents-of-the-csv-files-5" class="level2" data-number="31">
<h2 data-number="31" class="anchored" data-anchor-id="contents-of-the-csv-files-5"><span class="header-section-number">31</span> Contents of the CSV Files</h2>
<p>Below is a detailed explanation of the SQL Server-related CSV files and how they relate to one another:</p>
<section id="publication.csv-5" class="level3" data-number="31.1">
<h3 data-number="31.1" class="anchored" data-anchor-id="publication.csv-5"><span class="header-section-number">31.1</span> <strong>publication.csv</strong></h3>
<ul>
<li><strong>Description</strong>: This file contains information about publications, which are the central entities in this dataset.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>id</code>: Unique identifier for each publication.</li>
<li><code>title</code>: Title of the publication.</li>
<li><code>doi</code>: Digital Object Identifier of the publication.</li>
<li><code>year</code> and <code>month</code>: Publication date.</li>
<li>Other metadata such as <code>citation_count</code>, <code>pub_type</code>, etc.</li>
</ul></li>
</ul>
<p><strong>Sample Data</strong>:</p>
<!--\~~~markdown-->
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 59%">
<col style="width: 22%">
<col style="width: 5%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th>id</th>
<th>title</th>
<th>doi</th>
<th>year</th>
<th>month</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>321613</td>
<td>New estimates for CRNA vacancies</td>
<td></td>
<td>2009</td>
<td>4</td>
</tr>
<tr class="even">
<td>321614</td>
<td>Crossing county lines: The impact of crash location and driver’s…</td>
<td>10.1016/j.aap.2006…</td>
<td>2006</td>
<td>7</td>
</tr>
</tbody>
</table>
</section>
<section id="dataset_alias.csv-5" class="level3" data-number="31.2">
<h3 data-number="31.2" class="anchored" data-anchor-id="dataset_alias.csv-5"><span class="header-section-number">31.2</span> <strong>dataset_alias.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Contains all the aliases (alternative names) of datasets. This helps in identifying datasets that might be referred to by different names in publications.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>alias_id</code>: Unique identifier for each alias.</li>
<li><code>parent_alias_id</code>: Identifies the main alias for a dataset. If <code>parent_alias_id</code> equals <code>alias_id</code>, it is the primary alias.</li>
<li><code>alias</code>: The alias name of the dataset.</li>
</ul></li>
</ul>
<p><strong>How to Use</strong>:</p>
<ul>
<li>To find the main alias of a dataset, look for rows where <code>alias_id</code> equals <code>parent_alias_id</code>.</li>
<li>To find all aliases of a dataset, filter by <code>parent_alias_id</code> corresponding to the main alias.</li>
</ul>
<p><strong>Sample Data</strong>:</p>
<!--\~~~markdown-->
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 20%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>id</th>
<th>alias_id</th>
<th>parent_alias_id</th>
<th>alias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1676</td>
<td>87</td>
<td>89</td>
<td>Census of Agriculture</td>
</tr>
<tr class="even">
<td>1673</td>
<td>12</td>
<td>282</td>
<td>ARMS Farm Financial and Crop Production Practices</td>
</tr>
</tbody>
</table>
</section>
<section id="dyad.csv-5" class="level3" data-number="31.3">
<h3 data-number="31.3" class="anchored" data-anchor-id="dyad.csv-5"><span class="header-section-number">31.3</span> <strong>dyad.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Represents the mentions of dataset aliases found within publications. Acts as a linking table between <code>publication.csv</code> and <code>dataset_alias.csv</code>.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>id</code>: Unique identifier for each dyad (mention).</li>
<li><code>publication_id</code>: References the <code>id</code> in <code>publication.csv</code>.</li>
<li><code>alias_id</code>: References the <code>alias_id</code> in <code>dataset_alias.csv</code>.</li>
<li><code>mention_candidate</code>: The actual text mentioning the dataset in the publication.</li>
</ul></li>
</ul>
<p><strong>Sample Data</strong>:</p>
<!--\~~~markdown-->
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>publication_id</th>
<th>alias_id</th>
<th>mention_candidate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2569</td>
<td>1211491</td>
<td>87</td>
<td>census of agriculture</td>
</tr>
<tr class="even">
<td>2573</td>
<td>1199598</td>
<td>88</td>
<td>usda census of agriculture</td>
</tr>
</tbody>
</table>
</section>
<section id="model.csv-5" class="level3" data-number="31.4">
<h3 data-number="31.4" class="anchored" data-anchor-id="model.csv-5"><span class="header-section-number">31.4</span> <strong>model.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Lists the different models or methods used to identify dataset mentions within publications.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>id</code>: Unique identifier for each model.</li>
<li><code>name</code>: Name of the model (e.g., <code>string_matching</code>, <code>refmatch</code>).</li>
</ul></li>
</ul>
<p><strong>Relevant Models</strong>:</p>
<ul>
<li><strong>Model ID 1</strong>: <code>string_matching</code></li>
<li><strong>Model ID 5</strong>: <code>refmatch</code></li>
</ul>
<p>These are the models we are focusing on to compare with data extracted from OpenAlex, as no Kaggle model has been applied there.</p>
<p><strong>Sample Data</strong>:</p>
<!--\~~~markdown-->
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>string_matching</td>
</tr>
<tr class="even">
<td>5</td>
<td>refmatch</td>
</tr>
</tbody>
</table>
</section>
<section id="dyad_model.csv-5" class="level3" data-number="31.5">
<h3 data-number="31.5" class="anchored" data-anchor-id="dyad_model.csv-5"><span class="header-section-number">31.5</span> <strong>dyad_model.csv</strong></h3>
<ul>
<li><strong>Description</strong>: Connects dyads with the models that identified them. Allows filtering dyads based on the models used.</li>
<li><strong>Key Columns</strong>:
<ul>
<li><code>dyad_id</code>: References the <code>id</code> in <code>dyad.csv</code>.</li>
<li><code>model_id</code>: References the <code>id</code> in <code>model.csv</code>.</li>
</ul></li>
</ul>
<p><strong>How to Use</strong>:</p>
<ul>
<li>To filter dyads (and thus publications) identified by specific models, perform an inner join with <code>dyad.csv</code> on <code>dyad_id</code> and filter by <code>model_id</code>.</li>
</ul>
<p><strong>Sample Data</strong>:</p>
<!--\~~~markdown-->
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>dyad_id</th>
<th>model_id</th>
<th>score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4928</td>
<td>2569</td>
<td>1</td>
<td>2.0</td>
</tr>
<tr class="even">
<td>4929</td>
<td>2569</td>
<td>4</td>
<td>1.0</td>
</tr>
<tr class="odd">
<td>4930</td>
<td>2569</td>
<td>2</td>
<td>1.0</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="how-the-files-are-related-2" class="level2" data-number="32">
<h2 data-number="32" class="anchored" data-anchor-id="how-the-files-are-related-2"><span class="header-section-number">32</span> How the Files are Related</h2>
<p>The files are structured to represent entities (publications, journals, institutions, authors) and their relationships. The main publication data is in <code>publications_main.csv</code>, and the details about journals, institutions, and authors are in their respective files. The link files (<code>publication_journal_links.csv</code>, <code>publication_institution_links.csv</code>, <code>publication_author_links.csv</code>) represent the many-to-many relationships between publications and these entities.</p>
<p>By using the OpenAlex identifiers, you can join these files to perform comprehensive analyses. For example:</p>
<ul>
<li>To find all publications by a specific author, you can use <code>authors.csv</code> to find the author’s <code>author_openalex_id</code> and then use <code>publication_author_links.csv</code> to find the associated publications.</li>
<li>To analyze the distribution of publications across journals, you can join <code>publications_main.csv</code>, <code>publication_journal_links.csv</code>, and <code>journals.csv</code> on <code>publication_openalex_id</code> and <code>journal_openalex_id</code>.</li>
</ul>
</section>
<section id="how-to-extract-publications-for-a-specific-dataset-5" class="level2" data-number="33">
<h2 data-number="33" class="anchored" data-anchor-id="how-to-extract-publications-for-a-specific-dataset-5"><span class="header-section-number">33</span> How to Extract Publications for a Specific Dataset</h2>
<p>To find all publications associated with a particular dataset, such as the <strong>NASS Census of Agriculture</strong>, follow these steps:</p>
<ol type="1">
<li><p><strong>Identify the Main Alias</strong>:</p>
<ul>
<li>Find the <code>alias_id</code> where <code>alias_id</code> equals <code>parent_alias_id</code> for the dataset.</li>
<li>For <strong>NASS Census of Agriculture</strong>, the main alias has <code>alias_id</code> = <strong>89</strong>.</li>
</ul></li>
<li><p><strong>Get All Aliases</strong>:</p>
<ul>
<li>In <code>dataset_alias.csv</code>, filter rows where <code>parent_alias_id</code> equals <strong>89</strong>.</li>
<li>This gives you all aliases associated with the <strong>NASS Census of Agriculture</strong> dataset.</li>
</ul></li>
<li><p><strong>Link Aliases to Publications</strong>:</p>
<ul>
<li>In <code>dyad.csv</code>, filter rows where <code>alias_id</code> matches any of the <code>alias_id</code>s obtained in step 2.</li>
<li>This will give you <code>publication_id</code>s of publications mentioning any alias of the dataset.</li>
</ul></li>
<li><p><strong>Retrieve Publication Details</strong>:</p>
<ul>
<li>Using the <code>publication_id</code>s from step 3, retrieve the corresponding records from <code>publication.csv</code>.</li>
</ul></li>
</ol>
</section>
<section id="filtering-publications-by-specific-models-5" class="level2" data-number="34">
<h2 data-number="34" class="anchored" data-anchor-id="filtering-publications-by-specific-models-5"><span class="header-section-number">34</span> Filtering Publications by Specific Models</h2>
<p>Since we’re interested in mentions identified by the <strong><code>string_matching</code></strong> and <strong><code>refmatch</code></strong> models (models with <code>id</code> 1 and 5), follow these steps:</p>
<ol type="1">
<li><p><strong>Filter Dyads by Model</strong>:</p>
<ul>
<li>In <code>dyad_model.csv</code>, filter rows where <code>model_id</code> is <strong>1</strong> or <strong>5</strong>.</li>
<li>This gives you <code>dyad_id</code>s linked to these models.</li>
</ul></li>
<li><p><strong>Get Relevant Dyads</strong>:</p>
<ul>
<li>Perform an inner join with <code>dyad.csv</code> on <code>dyad_id</code>.</li>
<li>This filters dyads to only those identified by the specified models.</li>
</ul></li>
<li><p><strong>Proceed as Before</strong>:</p>
<ul>
<li>Continue with the steps in the previous section, but using the filtered dyads from step 2.</li>
</ul></li>
</ol>
</section>
<section id="practical-example-5" class="level2" data-number="35">
<h2 data-number="35" class="anchored" data-anchor-id="practical-example-5"><span class="header-section-number">35</span> Practical Example</h2>
<p><strong>Objective</strong>: Find all publications mentioning the <strong>NASS Census of Agriculture</strong> dataset using the <code>string_matching</code> and <code>refmatch</code> models.</p>
<p><strong>Steps</strong>:</p>
<ol type="1">
<li><p><strong>Find Main Alias ID</strong>:</p>
<ul>
<li>Main alias <code>alias_id</code> = <strong>89</strong>.</li>
</ul></li>
<li><p><strong>Get All Aliases</strong>:</p>
<ul>
<li>From <code>dataset_alias.csv</code>, extract all <code>alias_id</code>s where <code>parent_alias_id</code> = <strong>89</strong>.</li>
</ul></li>
<li><p><strong>Filter Dyads by Models</strong>:</p>
<ul>
<li>From <code>dyad_model.csv</code>, get <code>dyad_id</code>s where <code>model_id</code> is <strong>1</strong> or <strong>5</strong>.</li>
</ul></li>
<li><p><strong>Get Dyads for Dataset</strong>:</p>
<ul>
<li>From <code>dyad.csv</code>, select rows where:
<ul>
<li><code>alias_id</code> is in the list from step 2, and</li>
<li><code>id</code> (dyad_id) is in the list from step 3.</li>
</ul></li>
</ul></li>
<li><p><strong>Retrieve Publications</strong>:</p>
<ul>
<li>Use <code>publication_id</code>s from the filtered dyads to get detailed information from <code>publication.csv</code>.</li>
</ul></li>
</ol>
</section>
<section id="sample-data-illustration-5" class="level2" data-number="36">
<h2 data-number="36" class="anchored" data-anchor-id="sample-data-illustration-5"><span class="header-section-number">36</span> Sample Data Illustration</h2>
<p><strong>From <code>dataset_alias.csv</code></strong>:</p>
<!--\~~~markdown-->
<table class="caption-top table">
<thead>
<tr class="header">
<th>alias_id</th>
<th>parent_alias_id</th>
<th>alias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>87</td>
<td>89</td>
<td>Census of Agriculture</td>
</tr>
<tr class="even">
<td>88</td>
<td>89</td>
<td>USDA Census of Agriculture</td>
</tr>
</tbody>
</table>
<p><strong>From <code>dyad.csv</code></strong>:</p>
<!--\~~~markdown-->
<table class="caption-top table">
<thead>
<tr class="header">
<th>id</th>
<th>publication_id</th>
<th>alias_id</th>
<th>mention_candidate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2569</td>
<td>1211491</td>
<td>87</td>
<td>census of agriculture</td>
</tr>
<tr class="even">
<td>2573</td>
<td>1199598</td>
<td>88</td>
<td>usda census of agriculture</td>
</tr>
</tbody>
</table>
<p><strong>From <code>dyad_model.csv</code></strong> (filtered for <code>model_id</code> 1 or 5):</p>
<!--\~~~markdown-->
<table class="caption-top table">
<thead>
<tr class="header">
<th>dyad_id</th>
<th>model_id</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2569</td>
<td>1</td>
</tr>
<tr class="even">
<td>2573</td>
<td>5</td>
</tr>
</tbody>
</table>
<p><strong>Resulting Publications</strong>:</p>
<ul>
<li>Publications with <code>id</code> <strong>1211491</strong> and <strong>1199598</strong> from <code>publication.csv</code>.</li>
</ul>
</section>
</div>
</div>
</div>
<p>By following the steps outlined above, you can effectively navigate the dataset to extract publications related to specific datasets and identified by particular models. This structured approach allows for targeted analysis and comparison with data from sources like OpenAlex.</p>
<p>Keep in mind that the OpenAlex data now may associate a single publication with multiple datasets, and due to the direct application of aliases and flag terms (with no optimizations), certain datasets like the NASS Census of Agriculture might show fewer publications than before.</p>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>