<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-04-28">

<title>Methodology for Comparing Citation Database Coverage of Dataset Usage – Citation Database Assessment</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./conclusions.html" rel="next">
<link href="./workflow/results/compare_pub_data.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./report.html">Findings</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Citation Database Assessment</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/laurenchenarides/compare_scopus_openalex_report" title="" class="quarto-navigation-tool px-1" aria-label="GitHub Repository"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./home.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Report Summary</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./terminology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Terminology</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project Background</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project Workflow</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./workflow/step01/define_data_assets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Step 01: Define Data Assets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./workflow/step02_01/extract_dataset_mentions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Step 02: Extract Dataset Mentions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./workflow/step02_02/create_seed_corpus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Creating a Seed Corpus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./workflow/step03/clean_pub_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Step 03: Clean Publication Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./workflow/results/compare_pub_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Step 04: Compare Results</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./report.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Findings</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conclusions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conclusions</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendices/app_crosswalk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Schemas</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./appendices/app_databases.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reference Files</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendices/app_scopus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Scopus Data Dictionary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendices/app_openalex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">OpenAlex Data Dictionary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendices/app_dimensions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dimensions Data Dictionary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendices/app_ipeds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Classifying Institutions with the IPEDS Database</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendices/app_msi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Identifying Minority Serving Institutions (MSIs)</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview"><span class="header-section-number">1</span> Overview</a></li>
  <li><a href="#data-collection" id="toc-data-collection" class="nav-link" data-scroll-target="#data-collection"><span class="header-section-number">2</span> Data Collection</a>
  <ul class="collapse">
  <li><a href="#scopus-approach" id="toc-scopus-approach" class="nav-link" data-scroll-target="#scopus-approach"><span class="header-section-number">2.1</span> Scopus Approach</a></li>
  <li><a href="#openalex-approach" id="toc-openalex-approach" class="nav-link" data-scroll-target="#openalex-approach"><span class="header-section-number">2.2</span> OpenAlex Approach</a>
  <ul class="collapse">
  <li><a href="#full-text-search-approach" id="toc-full-text-search-approach" class="nav-link" data-scroll-target="#full-text-search-approach"><span class="header-section-number">2.2.1</span> Full-Text Search Approach</a></li>
  <li><a href="#seed-corpus-approach" id="toc-seed-corpus-approach" class="nav-link" data-scroll-target="#seed-corpus-approach"><span class="header-section-number">2.2.2</span> Seed Corpus Approach</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#results-comparing-publication-and-journal-coverage" id="toc-results-comparing-publication-and-journal-coverage" class="nav-link" data-scroll-target="#results-comparing-publication-and-journal-coverage"><span class="header-section-number">3</span> Results Comparing Publication and Journal Coverage</a>
  <ul class="collapse">
  <li><a href="#method-1-full-text-search" id="toc-method-1-full-text-search" class="nav-link" data-scroll-target="#method-1-full-text-search"><span class="header-section-number">3.1</span> Method 1 (Full Text Search)</a></li>
  <li><a href="#method-2-seed-corpus-approach" id="toc-method-2-seed-corpus-approach" class="nav-link" data-scroll-target="#method-2-seed-corpus-approach"><span class="header-section-number">3.2</span> Method 2 (Seed Corpus Approach)</a></li>
  </ul></li>
  <li><a href="#results-comparing-publication-coverage-disaggregated-by-journal" id="toc-results-comparing-publication-coverage-disaggregated-by-journal" class="nav-link" data-scroll-target="#results-comparing-publication-coverage-disaggregated-by-journal"><span class="header-section-number">4</span> Results Comparing Publication Coverage Disaggregated by Journal</a>
  <ul class="collapse">
  <li><a href="#method-1-full-text-search-1" id="toc-method-1-full-text-search-1" class="nav-link" data-scroll-target="#method-1-full-text-search-1"><span class="header-section-number">4.1</span> Method 1 (Full-Text Search)</a></li>
  <li><a href="#method-2-seed-corpus-approach-1" id="toc-method-2-seed-corpus-approach-1" class="nav-link" data-scroll-target="#method-2-seed-corpus-approach-1"><span class="header-section-number">4.2</span> Method 2 (Seed Corpus Approach)</a></li>
  </ul></li>
  <li><a href="#institutional-comparison" id="toc-institutional-comparison" class="nav-link" data-scroll-target="#institutional-comparison"><span class="header-section-number">5</span> Institutional Comparison</a>
  <ul class="collapse">
  <li><a href="#step-1-clean-ipeds-and-msi-data" id="toc-step-1-clean-ipeds-and-msi-data" class="nav-link" data-scroll-target="#step-1-clean-ipeds-and-msi-data">Step 1: Clean IPEDS and MSI data</a></li>
  </ul></li>
  <li><a href="#summary-of-findings" id="toc-summary-of-findings" class="nav-link" data-scroll-target="#summary-of-findings"><span class="header-section-number">6</span> Summary of Findings</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/laurenchenarides/compare_scopus_openalex_report/edit/main/report.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/laurenchenarides/compare_scopus_openalex_report/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div><div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="report.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Methodology for Comparing Citation Database Coverage of Dataset Usage</h1>
<p class="subtitle lead">Findings</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 28, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="overview" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Overview</h1>
<p><a href="report.pdf" class="btn btn-success">Download PDF Version</a></p>
<p>This report compares the differences between the Scopus and OpenAlex citation databases in their tracking of dataset mentions. The Census of Agriculture, produced by the USDA National Agricultural Statistical Services (NASS), provides information on U.S. farming operations, including production practices and land use. This dataset is used as a case study in this report to systematically compare the coverage, overlap, and differences in publications indexed by the two citation databases. The Census of Agriculture (also referred to as the “Ag Census”) is selected for its frequent use in agricultural and economic research, making it an ideal dataset for assessing differences in publication coverage between Scopus and OpenAlex.</p>
<!-- \footnote{Part of the purpose of this case study is also to validate the assumption that the Ag Census is frequently and consistently cited in the scholarly literature.} -->
<p><strong>Secondary Objective: Institutional Representation</strong></p>
<p>In addition to examining dataset mention coverage, the report also evaluates differences in institutional representation across Scopus and OpenAlex. Publication affiliation data are linked to institutional records using IPEDS identifiers to create a harmonized dataset across sources. This allows for assessment of how each citation database represents institutions based on characteristics such as control (public or private), degree level, MSI designation, and geographic location. Special attention is given to coverage of underrepresented institutions and Minority-Serving Institutions (MSIs). This analysis informs broader conversations about equity, transparency, and accountability in research data infrastructure.</p>
</section>
<section id="data-collection" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Data Collection</h1>
<p>To compare coverage across the two citation databases, publications that mention the Ag Census must first be identified. The methods used to identify dataset mentions in Scopus and OpenAlex are described below.</p>
<section id="scopus-approach" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="scopus-approach"><span class="header-section-number">2.1</span> Scopus Approach</h2>
<p>The first citation database used is Scopus, a publication catalog managed by Elsevier. Ideally, direct Scopus API access would have been used to query full publication text for mentions of the Census of Agriculture. However, the project did not have access to the Scopus API. Only Elsevier, serving as a project partner, was able to execute queries within the Scopus environment. Consequently, the dataset mention search relied on outputs provided by Elsevier rather than independent querying.</p>
<p>Because of these constraints, a seed corpus approach was applied. First, Elsevier matched the names and aliases of selected datasets, including the Census of Agriculture, against full-text records available through ScienceDirect and reference sections of Scopus publications published between 2017 and 2023. This initial step identified journals, authors, and topics most likely to reference the Ag Census. A targeted search corpus was then constructed, narrowing the scope to approximately 1.45 million publications.</p>
<p>Several methods were used to identify mentions of USDA datasets in Scopus publications. First, a reference search was conducted, using exact-text matching across publication reference lists to capture formal citations of datasets. Second, full-text searches were performed using machine learning models applied to publication bodies, identifying less formal mentions of datasets. Third, machine learning routines developed through the 2021 Kaggle competition were applied to the full-text corpus to improve detection of dataset mentions, including instances where references were indirect or less structured. Details about the three machine learning models used are available <a href="https://github.com/democratizingdata/democratizingdata-ml-algorithms/blob/main/README.md">here</a>.</p>
<p>Because direct access to full publication text was not available, Elsevier shared only the extracted snippets and limited metadata. Manual validation, aided by the use of keyword flags (e.g., “USDA,” “NASS”), confirmed whether identified mentions accurately referred to the Census of Agriculture. To manage validation costs, only publications with at least one U.S.-based author were reviewed.</p>
<p>Full documentation of the Scopus search routine, including query construction and extraction procedures, is available at the project’s <a href="https://laurenchenarides.github.io/compare_scopus_openalex_report/workflow/step02_01/extract_dataset_mentions.html">report website</a>.</p>
</section>
<section id="openalex-approach" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="openalex-approach"><span class="header-section-number">2.2</span> OpenAlex Approach</h2>
<p>The second citation database used is OpenAlex, an open catalog of scholarly publications. OpenAlex offers public access to metadata and, when available, full-text content for open-access publications through its <a href="https://docs.openalex.org/how-to-use-the-api/api-overview">API</a>. Unlike Scopus, which provides controlled access to licensed content, OpenAlex indexes only publications that are openly available or for which open metadata has been provided by publishers.</p>
<p>For OpenAlex, two approaches were used to identify publications referencing the Census of Agriculture. The first approach relied on a full-text search across OpenAlex publication records. The second approach applied a seed corpus methodology, similar to the strategy used for Scopus, to address limitations observed in the initial full-text search.</p>
<section id="full-text-search-approach" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="full-text-search-approach"><span class="header-section-number">2.2.1</span> Full-Text Search Approach</h3>
<p>The methodology for collecting mentions of USDA datasets in OpenAlex relied on constructing search queries that combined dataset “aliases” and associated “flag terms” within the text of scholarly works. Dataset aliases represented alternative ways researchers refer to a dataset, such as variations on the Census of Agriculture’s official name. Flag terms represented the institutions or agencies responsible for maintaining the dataset. The combination of dataset alias and flag terms ensured that retrieved publications made an explicit connection to the correct data source. A mention was recorded only if at least one alias and one flag term appeared in the same publication, thereby increasing the likelihood of capturing genuine dataset references rather than incidental matches to individual words.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>To implement these searches efficiently, the OpenAlex API was accessed using the <code>pyalex</code> Python package.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>Search queries were constructed based on OpenAlex’s public API documentation, using both the <a href="https://docs.openalex.org/api-entities/works/filter-works">“Filter Works”</a> and <a href="https://docs.openalex.org/api-entities/works/search-works">“Search Works”</a> endpoints. Filtering parameters were applied to restrict results to English-language publications, published after 2017, classified as articles or reviews, and available through open-access sources.</p>
<p>Boolean logic was used to define the text search structure. For the Census of Agriculture, the query grouped several dataset aliases, including “Census of Agriculture,” “USDA Census of Agriculture,” “Agricultural Census,” and “USDA Census.” These aliases were combined using an <code>OR</code> operator. Separately, flag terms including “USDA,” “U.S. Department of Agriculture,” “United States Department of Agriculture,” “NASS,” and “National Agricultural Statistics Service” were also grouped using an <code>OR</code> operator. The final query ensured that both an alias and a flag term appeared by connecting the two groups with an <code>AND</code> operator:</p>
<blockquote class="blockquote">
<p>(“NASS Census of Agriculture” OR “Census of Agriculture” OR “USDA Census of Agriculture” OR “Agricultural Census” OR “USDA Census” OR “AG Census”) AND (USDA OR “US Department of Agriculture” OR “United States Department of Agriculture” OR NASS OR “National Agricultural Statistics Service”)</p>
</blockquote>
<p>This structure required that each publication mention both a recognized variant of the Census of Agriculture name and a reference to the institution responsible for producing it.</p>
<p>Publications matching the query were returned in JSON format, based on the OpenAlex <a href="https://docs.openalex.org/api-entities/works/work-object">“Work object”</a> schema. Each record included metadata fields such as: - <code>display_name</code> (publication title) - <code>authorships</code> (authors and affiliations) - <code>host_venue.display_name</code> (journal) - <code>doi</code> (digital object identifier) - <code>concepts</code> (topics) - <code>cited_by_count</code> (citation counts) - <code>type</code> (publication type, e.g., “article”, “book-chapter”) - <code>publication_year</code> (year article was publish) - <code>language</code> (language, English only) - <code>is_oa</code> (open access)</p>
<p>Although a range of publication types were retrieved—including articles, book chapters, dissertations, preprints, and reviews—approximately 80–85 percent were classified as articles. To standardize the dataset for downstream analysis, results were filtered during the search process to retain only records identified as <code>type = article</code>. This step removed preprints and non-final versions of works, supporting a more standardized analysis of dataset mentions in peer-reviewed literature.</p>
<p>The code used to implement this querying and filtering process is publicly available <a href="https://github.com/laurenchenarides/compare_scopus_openalex_report">here</a>.</p>
<section id="limitations-of-full-text-approach" class="level4" data-number="2.2.1.1">
<h4 data-number="2.2.1.1" class="anchored" data-anchor-id="limitations-of-full-text-approach"><span class="header-section-number">2.2.1.1</span> Limitations of Full-Text Approach</h4>
<p>Although the OpenAlex API provides full-text search capabilities, limitations in how publication content is ingested and indexed introduce challenges for identifying dataset mentions accurately.</p>
<p>OpenAlex receives publication text through two primary ingestion methods: PDF extraction and <a href="https://docs.openalex.org/api-entities/works/get-n-grams">n-grams delivery</a>. In the PDF ingestion method, OpenAlex extracts text directly from the article PDF. However, the references section is not included in the searchable text. References are processed separately to create citation pointers between scholarly works, meaning that mentions of datasets appearing only in bibliographies are not discoverable through full-text search.</p>
<p>In the n-grams ingestion method, OpenAlex does not receive the full article text. Instead, it receives a set of extracted word sequences (n-grams) from the publisher or author. These n-grams represent fragments of text—typically short sequences of one, two, or three words—which are not guaranteed to preserve full continuous phrases. As a result, complete dataset names may be broken apart or omitted, reducing the likelihood that search queries match the intended aliases.</p>
<p>These ingestion and indexing limitations affect the completeness of results when relying solely on OpenAlex full-text search. Mentions of the Census of Agriculture and other USDA datasets that appear either exclusively in references or are fragmented within n-grams may be missed. To address these limitations, an alternative search strategy was developed based on constructing a filtered seed corpus of publications for local full-text analysis.</p>
</section>
</section>
<section id="seed-corpus-approach" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="seed-corpus-approach"><span class="header-section-number">2.2.2</span> Seed Corpus Approach</h3>
<p>To address limitations in OpenAlex’s full-text indexing methods, a seed corpus approach was applied. The objective was to create a filtered set of publications for local text search to better capture mentions of the Census of Agriculture and related USDA datasets.</p>
<p>To construct the seed corpus, publications were filtered based on several criteria:</p>
<ul>
<li>Language: English</li>
<li>Publication Year: Post-2017</li>
<li>Publication Type: Articles and reviews</li>
<li>Open Access Status: Open-access publications only</li>
</ul>
<p>Filtering was further refined by selecting publications associated with high-relevance topics (<a href="#tbl-top25topics" class="quarto-xref">Table&nbsp;1</a>) lists the top 25 topics), top publishing journals (<a href="#tbl-top25journals" class="quarto-xref">Table&nbsp;2</a>) lists the top 25 journals), and U.S.-affiliated authors (<a href="#tbl-top25authors" class="quarto-xref">Table&nbsp;3</a>) lists the top 25 authors).</p>
<p>Each table presents two key columns to help interpret the selection process. The First Run Count refers to the number of publications linked to each entity (whether a topic, journal, or author) based on metadata from OpenAlex’s full-text search feature. This count reflects how often USDA datasets were mentioned within the full text of publications associated with a particular entity. The OpenAlex Total Count represents the total number of publications linked to that entity in the broader OpenAlex database, without applying any filters related to dataset mentions.</p>
<p>To create a more focused and manageable search corpus, we selected the top 25 entities in each category based on their First Run Count. This approach prioritizes journals, topics, and authors where USDA datasets are most frequently mentioned in the full text, which we interpret as being more representative of actual research activity involving these datasets. It also substantially reduces the workload by limiting the number of publications that need to be retrieved and processed.</p>
<p>Choosing this approach has a few important implications. First, it likely increases the relevance of the resulting corpus by concentrating on publications where USDA data are actively cited or discussed, rather than simply associated with a broader research area. Second, it helps avoid the need to download and process an unmanageable number of PDFs—estimated at around 1.7 million if all identified entities were included. However, this method may introduce some selection bias by favoring entities with higher immediate visibility in the first search pass. Some relevant but less frequently mentioned entities might be excluded, meaning that while efficiency improves, full comprehensiveness is slightly sacrificed. Overall, this tradeoff supports a practical balance between depth and feasibility in building the final dataset.</p>
<div id="tbl-top25topics" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-top25topics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Top 25 Topics by First Run Count
</figcaption>
<div aria-describedby="tbl-top25topics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 57%">
<col style="width: 14%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th>Topic ID</th>
<th>Topic Name</th>
<th>First Run Count</th>
<th>OpenAlex Total Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>T11610</td>
<td>Impact of Food Insecurity on Health Outcomes</td>
<td>549</td>
<td>78661</td>
</tr>
<tr class="even">
<td>T10010</td>
<td>Global Trends in Obesity and Overweight Research</td>
<td>272</td>
<td>111686</td>
</tr>
<tr class="odd">
<td>T11066</td>
<td>Comparative Analysis of Organic Agricultural Practices</td>
<td>247</td>
<td>41275</td>
</tr>
<tr class="even">
<td>T12253</td>
<td>Urban Agriculture and Community Development</td>
<td>222</td>
<td>27383</td>
</tr>
<tr class="odd">
<td>T10367</td>
<td>Agricultural Innovation and Livelihood Diversification</td>
<td>186</td>
<td>49818</td>
</tr>
<tr class="even">
<td>T11464</td>
<td>Impact of Homelessness on Health and Well-being</td>
<td>175</td>
<td>101019</td>
</tr>
<tr class="odd">
<td>T12033</td>
<td>European Agricultural Policy and Reform</td>
<td>137</td>
<td>88980</td>
</tr>
<tr class="even">
<td>T10841</td>
<td>Discrete Choice Models in Economics and Health Care</td>
<td>126</td>
<td>66757</td>
</tr>
<tr class="odd">
<td>T10596</td>
<td>Maternal and Child Nutrition in Developing Countries</td>
<td>116</td>
<td>118727</td>
</tr>
<tr class="even">
<td>T11898</td>
<td>Impacts of Food Prices on Consumption and Poverty</td>
<td>113</td>
<td>29110</td>
</tr>
<tr class="odd">
<td>T11259</td>
<td>Sustainable Diets and Environmental Impact</td>
<td>109</td>
<td>45082</td>
</tr>
<tr class="even">
<td>T11311</td>
<td>Soil and Water Nutrient Dynamics</td>
<td>84</td>
<td>52847</td>
</tr>
<tr class="odd">
<td>T10235</td>
<td>Impact of Social Factors on Health Outcomes</td>
<td>81</td>
<td>86076</td>
</tr>
<tr class="even">
<td>T10439</td>
<td>Adaptation to Climate Change in Agriculture</td>
<td>77</td>
<td>27311</td>
</tr>
<tr class="odd">
<td>T11886</td>
<td>Risk Management and Vulnerability in Agriculture</td>
<td>73</td>
<td>44755</td>
</tr>
<tr class="even">
<td>T10226</td>
<td>Global Analysis of Ecosystem Services and Land Use</td>
<td>71</td>
<td>84104</td>
</tr>
<tr class="odd">
<td>T10866</td>
<td>Role of Mediterranean Diet in Health Outcomes</td>
<td>70</td>
<td>76894</td>
</tr>
<tr class="even">
<td>T10969</td>
<td>Optimal Operation of Water Resources Systems</td>
<td>70</td>
<td>97570</td>
</tr>
<tr class="odd">
<td>T10330</td>
<td>Hydrological Modeling and Water Resource Management</td>
<td>69</td>
<td>132216</td>
</tr>
<tr class="even">
<td>T11753</td>
<td>Forest Management and Policy</td>
<td>60</td>
<td>75196</td>
</tr>
<tr class="odd">
<td>T12098</td>
<td>Rural development and sustainability</td>
<td>54</td>
<td>62114</td>
</tr>
<tr class="even">
<td>T10111</td>
<td>Remote Sensing in Vegetation Monitoring and Phenology</td>
<td>52</td>
<td>56452</td>
</tr>
<tr class="odd">
<td>T10556</td>
<td>Global Cancer Incidence and Mortality Patterns</td>
<td>49</td>
<td>64063</td>
</tr>
<tr class="even">
<td>T11711</td>
<td>Impacts of COVID-19 on Global Economy and Markets</td>
<td>49</td>
<td>69059</td>
</tr>
<tr class="odd">
<td>T12724</td>
<td>Integrated Management of Water, Energy, and Food Resources</td>
<td>47</td>
<td>40148</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-top25journals" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-top25journals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Top 25 Journals by First Run Count
</figcaption>
<div aria-describedby="tbl-top25journals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 58%">
<col style="width: 13%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Journal ID</th>
<th>Journal Name</th>
<th>First Run Count</th>
<th>OpenAlex Total Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>S2764628096</td>
<td>Journal of Agriculture Food Systems and Community Development</td>
<td>57</td>
<td>825</td>
</tr>
<tr class="even">
<td>S115427279</td>
<td>Public Health Nutrition</td>
<td>51</td>
<td>3282</td>
</tr>
<tr class="odd">
<td>S206696595</td>
<td>Journal of Nutrition Education and Behavior</td>
<td>41</td>
<td>3509</td>
</tr>
<tr class="even">
<td>S15239247</td>
<td>International Journal of Environmental Research and Public Health</td>
<td>39</td>
<td>59130</td>
</tr>
<tr class="odd">
<td>S4210201861</td>
<td>Applied Economic Perspectives and Policy</td>
<td>39</td>
<td>647</td>
</tr>
<tr class="even">
<td>S10134376</td>
<td>Sustainability</td>
<td>35</td>
<td>87533</td>
</tr>
<tr class="odd">
<td>S5832799</td>
<td>Journal of Soil and Water Conservation</td>
<td>34</td>
<td>556</td>
</tr>
<tr class="even">
<td>S2739393555</td>
<td>Journal of Agricultural and Applied Economics</td>
<td>34</td>
<td>329</td>
</tr>
<tr class="odd">
<td>S202381698</td>
<td>PLoS ONE</td>
<td>30</td>
<td>143568</td>
</tr>
<tr class="even">
<td>S124372222</td>
<td>Renewable Agriculture and Food Systems</td>
<td>30</td>
<td>426</td>
</tr>
<tr class="odd">
<td>S200437886</td>
<td>BMC Public Health</td>
<td>28</td>
<td>18120</td>
</tr>
<tr class="even">
<td>S91754907</td>
<td>American Journal of Agricultural Economics</td>
<td>28</td>
<td>876</td>
</tr>
<tr class="odd">
<td>S18733340</td>
<td>Journal of the Academy of Nutrition and Dietetics</td>
<td>27</td>
<td>5301</td>
</tr>
<tr class="even">
<td>S78512408</td>
<td>Agriculture and Human Values</td>
<td>27</td>
<td>938</td>
</tr>
<tr class="odd">
<td>S110785341</td>
<td>Nutrients</td>
<td>25</td>
<td>30911</td>
</tr>
<tr class="even">
<td>S2764593300</td>
<td>Agricultural and Resource Economics Review</td>
<td>25</td>
<td>247</td>
</tr>
<tr class="odd">
<td>S4210212157</td>
<td>Frontiers in Sustainable Food Systems</td>
<td>23</td>
<td>3776</td>
</tr>
<tr class="even">
<td>S63571384</td>
<td>Food Policy</td>
<td>20</td>
<td>1069</td>
</tr>
<tr class="odd">
<td>S69340840</td>
<td>The Journal of Rural Health</td>
<td>20</td>
<td>749</td>
</tr>
<tr class="even">
<td>S4210234824</td>
<td>EDIS</td>
<td>18</td>
<td>3714</td>
</tr>
<tr class="odd">
<td>S19383905</td>
<td>Agricultural Finance Review</td>
<td>18</td>
<td>327</td>
</tr>
<tr class="even">
<td>S119228529</td>
<td>Journal of Hunger &amp; Environmental Nutrition</td>
<td>17</td>
<td>467</td>
</tr>
<tr class="odd">
<td>S43295729</td>
<td>Remote Sensing</td>
<td>14</td>
<td>33899</td>
</tr>
<tr class="even">
<td>S2738397068</td>
<td>Land</td>
<td>14</td>
<td>9774</td>
</tr>
<tr class="odd">
<td>S80485027</td>
<td>Land Use Policy</td>
<td>14</td>
<td>4559</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-top25authors" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-top25authors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Top 25 Authors by First Run Count Table
</figcaption>
<div aria-describedby="tbl-top25authors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 31%">
<col style="width: 22%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Author ID</th>
<th>Author Name</th>
<th>First Run Count</th>
<th>OpenAlex Total Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A5016803484</td>
<td>Heather A. Eicher‐Miller</td>
<td>15</td>
<td>140</td>
</tr>
<tr class="even">
<td>A5024975191</td>
<td>Edward A. Frongillo</td>
<td>13</td>
<td>351</td>
</tr>
<tr class="odd">
<td>A5055158106</td>
<td>Becca B.R. Jablonski</td>
<td>12</td>
<td>60</td>
</tr>
<tr class="even">
<td>A5047780964</td>
<td>Meredith T. Niles</td>
<td>11</td>
<td>200</td>
</tr>
<tr class="odd">
<td>A5076121862</td>
<td>Sheri D. Weiser</td>
<td>10</td>
<td>241</td>
</tr>
<tr class="even">
<td>A5068812455</td>
<td>Cindy W. Leung</td>
<td>10</td>
<td>170</td>
</tr>
<tr class="odd">
<td>A5062679478</td>
<td>J. Gordon Arbuckle</td>
<td>10</td>
<td>68</td>
</tr>
<tr class="even">
<td>A5015017711</td>
<td>Jeffrey K. O’Hara</td>
<td>10</td>
<td>27</td>
</tr>
<tr class="odd">
<td>A5081656928</td>
<td>Whitney E. Zahnd</td>
<td>9</td>
<td>147</td>
</tr>
<tr class="even">
<td>A5002438645</td>
<td>Phyllis C. Tien</td>
<td>8</td>
<td>244</td>
</tr>
<tr class="odd">
<td>A5035584432</td>
<td>Angela D. Liese</td>
<td>8</td>
<td>172</td>
</tr>
<tr class="even">
<td>A5027684365</td>
<td>Dayton M. Lambert</td>
<td>8</td>
<td>110</td>
</tr>
<tr class="odd">
<td>A5081012770</td>
<td>Linda J. Young</td>
<td>8</td>
<td>51</td>
</tr>
<tr class="even">
<td>A5008463933</td>
<td>Catherine Brinkley</td>
<td>8</td>
<td>34</td>
</tr>
<tr class="odd">
<td>A5030548116</td>
<td>Michele Ver Ploeg</td>
<td>8</td>
<td>33</td>
</tr>
<tr class="even">
<td>A5056021318</td>
<td>Nathan Hendricks</td>
<td>7</td>
<td>320</td>
</tr>
<tr class="odd">
<td>A5024248662</td>
<td>Adebola Adedimeji</td>
<td>7</td>
<td>137</td>
</tr>
<tr class="even">
<td>A5002732604</td>
<td>Julia A. Wolfson</td>
<td>7</td>
<td>137</td>
</tr>
<tr class="odd">
<td>A5038610136</td>
<td>Christopher N. Boyer</td>
<td>7</td>
<td>115</td>
</tr>
<tr class="even">
<td>A5044317355</td>
<td>Daniel Merenstein</td>
<td>7</td>
<td>113</td>
</tr>
<tr class="odd">
<td>A5006129622</td>
<td>Carmen Byker Shanks</td>
<td>7</td>
<td>103</td>
</tr>
<tr class="even">
<td>A5060802257</td>
<td>Tracey E. Wilson</td>
<td>7</td>
<td>102</td>
</tr>
<tr class="odd">
<td>A5050792105</td>
<td>Jennifer L. Moss</td>
<td>7</td>
<td>90</td>
</tr>
<tr class="even">
<td>A5032940306</td>
<td>Lisa Harnack</td>
<td>7</td>
<td>89</td>
</tr>
<tr class="odd">
<td>A5024127854</td>
<td>Eduardo Villamor</td>
<td>7</td>
<td>84</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The resulting seed corpus contained approximately 1,774,245 (<strong>CHECK WITH RAFAEL</strong>) unique publications. An initial download of full-texts achieved a success rate of approximately 35%, corresponding to an estimated 625,000 accessible full texts. Local full-text searches were planned using this subset to improve detection of dataset mentions beyond what was possible through OpenAlex’s built-in search functions.</p>
<p>While the seed corpus approach allowed more targeted retrieval, limitations remain. Full-text download success was constrained by incomplete or inaccessible open-access links, and processing the entire corpus was computationally intensive. Future efforts may require distributed processing or refined selection criteria to further improve efficiency.</p>
<p>Results from both methods are compared to assess differences in dataset mention detection across approaches.</p>
</section>
</section>
</section>
<section id="results-comparing-publication-and-journal-coverage" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Results Comparing Publication and Journal Coverage</h1>
<p>An objective of this report is to understand differences in publication coverage across Scopus and OpenAlex. Specifically, we ask: (1) how many and which publications referencing the Ag Census appear in each citation database, and (2) how many and which journals publishing these articles overlap between the two sources. In addition, this analysis aims to determine whether the different search approaches used to find dataset mentions in OpenAlex publications—the full-text search versus a seed-corpus approach—produce substantially different coverage.</p>
<p>This section presents two sets of results. In both cases, a seed-corpus approach is used to identify Ag Census publications in Scopus. We then compare these results to (i) publications identified through a full-text search in OpenAlex and (ii) publications identified using a seed-corpus approach in OpenAlex.</p>
<div class="cell">
<details class="code-fold">
<summary>Show R code used to generate the Venn Diagram</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>ui <span class="ot">&lt;-</span> <span class="fu">fluidPage</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plotOutput</span>(<span class="st">"venn_plot"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>server <span class="ot">&lt;-</span> <span class="cf">function</span>(input, output, session) {</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  output<span class="sc">$</span>venn_plot <span class="ot">&lt;-</span> <span class="fu">renderPlot</span>({</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    fit <span class="ot">&lt;-</span> <span class="fu">euler</span>(<span class="fu">c</span>(</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Scopus"</span> <span class="ot">=</span> <span class="dv">4207</span>,       <span class="co"># Only Scopus + estimated triple overlap</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>      <span class="st">"FullText"</span> <span class="ot">=</span> <span class="dv">761</span>,        <span class="co"># OpenAlex Full Text + estimated triple overlap</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>      <span class="st">"SeedCorpus"</span> <span class="ot">=</span> <span class="dv">940</span>,      <span class="co"># OpenAlex Seed Corpus + estimated triple overlap</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Scopus&amp;FullText"</span> <span class="ot">=</span> <span class="dv">405</span>,            <span class="co"># Scopus &amp; FullText total</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Scopus&amp;SeedCorpus"</span> <span class="ot">=</span> <span class="dv">263</span>,           <span class="co"># Scopus &amp; SeedCorpus total</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>      <span class="st">"FullText&amp;SeedCorpus"</span> <span class="ot">=</span> <span class="dv">5</span>,           <span class="co"># FullText &amp; SeedCorpus total</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Scopus&amp;FullText&amp;SeedCorpus"</span> <span class="ot">=</span> <span class="dv">100</span>         <span class="co"># assumed triple overlap</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">plot</span>(fit,</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>         <span class="at">fills =</span> <span class="fu">list</span>(<span class="at">fill =</span> <span class="fu">c</span>(<span class="st">"orange"</span>, <span class="st">"lightblue"</span>, <span class="st">"lightblue"</span>), <span class="at">alpha =</span> <span class="fl">0.6</span>),</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>         <span class="at">edges =</span> <span class="cn">TRUE</span>,</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>         <span class="at">labels =</span> <span class="fu">list</span>(<span class="at">font =</span> <span class="dv">4</span>),</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>         <span class="at">quantities =</span> <span class="cn">TRUE</span>,</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>         <span class="at">lty =</span> <span class="fu">c</span>(<span class="st">"solid"</span>, <span class="st">"dashed"</span>, <span class="st">"dashed"</span>),   <span class="co"># Line type: Scopus solid, OpenAlex dotted</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>         <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"black"</span>, <span class="st">"black"</span>)       <span class="co"># Border color: all black</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="fu">shinyApp</span>(ui, server)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Listening on http://127.0.0.1:4609</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Overlap of Scopus (paywall) and OpenAlex Full Text and Seed Corpus (open access) publications.</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="How to Read Venn Diagram (click to expand)">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
How to Read Venn Diagram (click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 54%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>Set Combination</th>
<th>Meaning</th>
<th>Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Scopus</td>
<td>Only Scopus</td>
<td>4207</td>
</tr>
<tr class="even">
<td>Full Text</td>
<td>Only OpenAlex Full Text</td>
<td>761</td>
</tr>
<tr class="odd">
<td>Seed Corpus</td>
<td>Only OpenAlex Seed Corpus</td>
<td>940</td>
</tr>
<tr class="even">
<td>Scopus ∩ Full Text</td>
<td>Publications in Scopus and Full Text (including triple overlap)</td>
<td>505</td>
</tr>
<tr class="odd">
<td>Scopus ∩ Seed Corpus</td>
<td>Publications in Scopus and Seed Corpus (including triple overlap)</td>
<td>363</td>
</tr>
<tr class="even">
<td>Full Text ∩ Seed Corpus</td>
<td>Publications in Full Text and Seed Corpus (including triple overlap)</td>
<td>105</td>
</tr>
<tr class="odd">
<td>Scopus ∩ Full Text ∩ Seed Corpus</td>
<td>Publications in all three sources</td>
<td>100</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<section id="method-1-full-text-search" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="method-1-full-text-search"><span class="header-section-number">3.1</span> Method 1 (Full Text Search)</h2>
<p>The first comparison looks at publication and journal coverage between the Scopus (using the seed-corpus method) and OpenAlex (using the full-text search). The results describe how many publications mention the Ag Census in each database and evaluates the degree of overlap between them.</p>
<p>Table 1 displays the coverage of publications that referenced the Ag Census data. The table distinguishes between results that appear in both databases (column 1), only in OpenAlex (column 2), and only in Scopus (column 3). Column 4 is a total of all distinct publications or journals across both databases. The first row reports the number of individual publications found in each category. The unit of analysis is at the publication level. The second row reports the number of journals that include the Ag Census publications, again broken out by their appearance in one or both datasets. The unit of analysis is at the journal level.</p>
<p><strong>ADD TABLE 1 HERE</strong></p>
<p>The main takeaway from Table 1 is that there is little overlap in publications and journals between the two databases when using OpenAlex’s full-text search. According to this table, there are 5,473 unique publications referencing the Ag Census across both citation databases, appearing in 2,686 unique journals, identified by their ISSNs. The number of overlapping publications is 505 (9.23%), with the majority of publications referencing Ag Census are picked up only by Scopus (4,207 or 76.87%), and a smaller share is identified only in OpenAlex (761 or 13.9%).</p>
<p>Journal coverage shows a similar pattern. Of the journals that include at least one Ag Census publication, 247 (9.2%) are shared between the two databases, 2,362 (87.9%) are found only in Scopus, 77 (2.9%) only in OpenAlex.</p>
<p>These results show that the coverage of publications mentioning the Ag Census and the journals in which they are found is much more extensive in Scopus, and suggest that OpenAlex’s full-text search along may miss many dataset mentions.</p>
</section>
<section id="method-2-seed-corpus-approach" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="method-2-seed-corpus-approach"><span class="header-section-number">3.2</span> Method 2 (Seed Corpus Approach)</h2>
<p>Based on the pattern observed from the full-text search in OpenAlex, the differences likely arise, at least in part, from limitations in how OpenAlex processes and indexes text. Specifically, we found that OpenAlex’s full-text search does not index references as searchable text—they are stored as pointers, not included in the searchable body of the publication. In addition, n-gram-level metadata that might capture mentions of the Ag Census outside the main text was not accessible for the full set of publications. To address these limitations and create a more consistent comparison with Scopus, we applied a seed-corpus approach to OpenAlex, targeting a curated set of authors, journals, and topics associated with Ag Census use.</p>
<p>While this method can overcome the limitations of the OpenAlex full-text search, it is computationally more intensive. To limit the cost of the search corpus method, a list of the top authors, topics, and journals is provided, as described above. This list serves as a set of filters through which the search corpus is applied. Mentions of the Ag Census are then searched for within publications meeting these criteria.</p>
<p><strong>ADD TABLE 2 HERE</strong></p>
<p>Next, we compare the degree of overlap across the different search methods, focusing on OpenAlex publications that also overlap with Scopus records. Specifically, we examine whether the OpenAlex full-text search and the OpenAlex seed-corpus approach identified the same publications and journals referencing the Census of Agriculture, or whether each method uncovered distinct sets of works.</p>
<p>Table 3 summarizes the overlap between publications identified through the two OpenAlex search methods, restricted to publications that also appear in Scopus. As reported earlier, 505 publications were identified in both Scopus and OpenAlex using the OpenAlex full-text search (Table 1), while 363 publications were identified using the OpenAlex seed-corpus approach (Table 2). Table 3 specifically shows how many of the 505 full-text search publications were also found in the seed-corpus set. The comparison reveals that 105 publications are shared between the two methods, representing 20.8% of the full-text set and 28.9% of the seed-corpus set. These results suggest that the choice of search strategy meaningfully influences which Scopus-linked publications are recovered in OpenAlex.</p>
<p><strong>ADD TABLE 3 HERE</strong></p>
<p>Table 4 summarizes the overlap between journals identified through the two OpenAlex search methods, restricted to journals linked to publications that also appear in Scopus. As noted previously, the OpenAlex full-text search and seed-corpus approach each identified a set of journals containing publications referencing the Census of Agriculture. Table 4 specifically shows how many journals were common to both sets. A total of 137 journals were shared between the two methods, representing 55.5% of the full-text set and 49.6% of the seed-corpus set. Among these shared journals, 19 were part of the original list of top journals used to construct the seed corpus.</p>
<p><strong>ADD TABLE 4 HERE</strong></p>
</section>
</section>
<section id="results-comparing-publication-coverage-disaggregated-by-journal" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Results Comparing Publication Coverage Disaggregated by Journal</h1>
<p>Now that we have compared journal coverage across the two citation databases, we next examine the publications within journals that are indexed in both Scopus and OpenAlex. We report these results for the full-text search approach and the seed-corpus approach in OpenAlex.</p>
<section id="method-1-full-text-search-1" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="method-1-full-text-search-1"><span class="header-section-number">4.1</span> Method 1 (Full-Text Search)</h2>
<p>Table 5 provides journal-level detail on the overlap between publications indexed in Scopus and OpenAlex, based on the full-text search results in OpenAlex. Each row corresponds to a journal included in the analysis. The set of journals included here matches the group of overlapping journals reported in Table 1—that is, journals where publications were found in both Scopus and OpenAlex.</p>
<p>The table is divided into two sections: overlap statistics and publication counts. The overlap statistics report three measures. The percentage labeled “% Both” indicates the share of a journal’s publications that were found in both Scopus and OpenAlex. “% Scopus” shows the share of publications that appeared only in Scopus, while “% OpenAlex” shows the share of publications that appeared only in OpenAlex. Together, these columns summarize how consistently each journal’s publications are represented across the two databases.</p>
<p>The publication counts section reports the number of overlapping and non-overlapping publications for each journal. “Pubs Both” shows the number of publications found in both Scopus and OpenAlex, while “Pubs Scopus” and “Pubs OpenAlex” show the number of publications found exclusively in one database. The final column, “Total Pubs,” provides the total number of distinct publications associated with each journal across both databases.</p>
<p>Finally, the table also includes each journal’s 2022 Scopus CiteScore to provide additional context on journal prominence.</p>
<p>Reading across a row, the table allows for direct comparison of database coverage at the journal level, highlighting journals where coverage between Scopus and OpenAlex aligns closely and those where substantial gaps exist.</p>
<p><strong>ADD TABLE 5 HERE</strong></p>
<p>To further characterize database coverage, we calculated weighted average CiteScores for the journals analyzed in Table 5. The weighted averages account for both the number of publications associated with each journal and the journal’s 2022 Scopus CiteScore. For Scopus, the weighted average CiteScore, calculated by weighting each journal’s CiteScore by its number of publications found in Scopus (including shared publications), is approximately 12.99. For OpenAlex, the weighted average CiteScore, using the number of publications found in OpenAlex (including shared publications), is slightly higher at 13.23.</p>
<p>These results suggest that, among the overlapping journals, OpenAlex tends to recover a slightly more citation-intensive set of publications compared to Scopus. However, the difference in weighted averages is modest, indicating broadly similar coverage of higher-impact journals across the two databases. To formally test the difference in weighted average CiteScores between Scopus and OpenAlex, we calculated a t-statistic for the difference in means. The resulting t-statistic is approximately -0.15, indicating that the difference between the two weighted averages is not statistically significant. This suggests that, within the set of overlapping journals analyzed, Scopus and OpenAlex recover a similarly citation-intensive set of publications.</p>
</section>
<section id="method-2-seed-corpus-approach-1" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="method-2-seed-corpus-approach-1"><span class="header-section-number">4.2</span> Method 2 (Seed Corpus Approach)</h2>
<p>We next examine the results obtained using the OpenAlex seed corpus approach.</p>
<p>Table 6 summarizes publication-level overlap statistics for journals identified using the seed corpus approach. As with Table 5, the table is restricted to journals associated with publications that overlap between Scopus and OpenAlex. The overlap statistics show the percentage of each journal’s publications found in both databases (% Both), found only in Scopus (% Scopus), or found only in OpenAlex (% OpenAlex). Publication counts are also reported separately for shared and database-specific publications, along with the total number of publications associated with each journal. Each journal’s 2022 Scopus CiteScore is included to provide additional context on journal prominence.</p>
<p><strong>ADD TABLE 6 HERE</strong></p>
<p>To further compare database coverage under the seed corpus approach, we calculated weighted average CiteScores for Scopus and OpenAlex. The weighted averages account for both the number of publications associated with each journal and the journal’s 2022 Scopus CiteScore. For Scopus, the weighted average CiteScore is approximately 11.90, while for OpenAlex it is higher at approximately 14.10.</p>
<p>A t-statistic for the difference in means was also calculated to assess whether the difference is statistically meaningful. The resulting t-statistic is approximately -2.18, indicating that the difference is statistically significant. These results suggest that, when using the seed corpus approach, OpenAlex recovers a more citation-intensive set of publications compared to Scopus.</p>
<!-- Journal matches are obtained for this table using the "ISSN_L" value in the OpenAlex search corpus. Next, we turn to evaluating the overlap based on either of the ISSN values made available from the search corpus. -->
</section>
</section>
<section id="institutional-comparison" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Institutional Comparison</h1>
<!-- <div style="background-color: #f9f5d7; padding: 10px; border-radius: 5px; border: 1px solid #ddd; margin-bottom: 0;"> -->
<!-- <strong> The results in this section compare institutional coverage across three major bibliographic databases: Scopus, OpenAlex, and Dimensions. </strong> </div>  -->
<p>Each of the featured citation databases represent some portion of the global research landscape, yet their inclusion criteria and institutional coverage vary in ways that may inform disparities. Our goal is to assess which institutions are represented in each source, with particular attention to coverage of underrepresented and Minority-Serving Institutions (MSIs). By building a harmonized dataset that links IPEDS identifiers to institutional records across Scopus, OpenAlex, and Dimensions, we aim to evaluate how these citation databases include or exclude institutions across institutional characteristics such as control, level, MSI status, and geography. This analysis informs a broader conversation about equity, transparency, and accountability in research data systems.</p>
<section id="step-1-clean-ipeds-and-msi-data" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="step-1-clean-ipeds-and-msi-data">Step 1: Clean IPEDS and MSI data</h2>
<p>In this section, I document the construction and visualization of MSI (Minority-Serving Institution) eligibility trends from 2017 to 2023, as part of the broader effort to compare institutional coverage across Scopus, OpenAlex, and Dimensions. To support that analysis, we needed a clean, panel-form dataset of U.S. higher education institutions, including consistent MSI designations over time. I compiled and cleaned data from multiple sources—the MSI Data Project (Nguyen et al., 2023) for 2017–2021 and Rutgers CMSI lists for 2022–2023—and merged these with IPEDS institutional data, filtered to include only 2- and 4-year institutions in the 50 U.S. states. I addressed inconsistencies in eligibility labels, resolved duplicates, and created summary measures of MSI eligibility by year. The resulting visualization highlights both the number and percent of institutions designated as MSIs over time, with a sharp increase observed in 2022. The accompanying plot and source code are included for transparency. All additional details are available in the IPEDS<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> and MSI<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> Appendices.</p>
<figure style="text-align: center;" class="figure">
<a href="data/ipeds_msi/msi_eligibility_plot.png" target="_blank"> <img src="data/ipeds_msi/msi_eligibility_plot.png" style="width:80%; height:auto;" alt="MSI Eligibility Plot" class="figure-img"> </a>
<figcaption style="font-size: 0.9em; margin-top: 0.5em;">
<em>Source code used to generate graphic:</em> <a href="https://github.com/laurenchenarides/compare_scopus_openalex_report/blob/main/data/ipeds_msi/build_ipeds_msi.R" target="_blank">Available here</a>.
</figcaption>
</figure>
</section>
</section>
<section id="summary-of-findings" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Summary of Findings</h1>
<p>This report compares the coverage of publications and journals referencing the Census of Agriculture across Scopus and OpenAlex, using two approaches for identifying relevant OpenAlex publications: a full-text search and a seed corpus approach.</p>
<p>Using the full-text search in OpenAlex, we found relatively limited overlap with Scopus. Only 9.2% of publications and 9.2% of journals referencing the Census of Agriculture appeared in both databases, with Scopus identifying a substantially larger share of relevant works. These results suggest that relying solely on OpenAlex’s full-text search may miss a significant number of dataset mentions.</p>
<p>Applying the seed corpus approach to OpenAlex improved overlap with Scopus and provided a more structured way to capture publications associated with known journals, authors, and topics. However, the percentage of overlapping publications referencing the Census of Agriculture is lower at 6.42% even though there is a slightly higher percentage of shared journals at 10.73%.</p>
<p>Comparing the overlap between the two OpenAlex methods reveals differences in underlying samples. Only 20.8% of full-text search publications were also found in the seed corpus set, and 28.9% of seed corpus publications matched those found in the full-text search. Journal-level overlap was somewhat higher, with 137 journals shared between the two methods (representing approximately 50–55% overlap across the two pools).</p>
<p>Publication-level comparisons disaggregated by journal showed that, under the full-text search approach, OpenAlex and Scopus recovered broadly similar sets of citation-intensive publications. The weighted average CiteScores were 13.23 for OpenAlex and 12.99 for Scopus, with a t-statistic of -0.15, indicating no statistically significant difference. In contrast, under the seed corpus approach, OpenAlex recovered a more citation-intensive set of publications, with a weighted average CiteScore of 14.10 compared to 11.90 for Scopus. The t-statistic of -2.18 indicates that this difference is statistically significant.</p>
<p>It is important to note that the full-text search and seed corpus approaches represent two distinct sampling methods within OpenAlex. The full-text search attempts to identify dataset mentions directly from the body of text available for a subset of publications, while the seed corpus approach relies on pre-selected journals, topics, and authors more likely to reference the Census of Agriculture. As a result, the pools of publications identified by each method are not strictly comparable: they are drawn from different underlying subsets of OpenAlex’s catalog. This context is important for interpreting differences in coverage and citation intensity across the two approaches.</p>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Initial drafts of the query incorrectly included terms like “NASS” and “USDA” in the alias list. This was corrected to ensure that aliases strictly referred to dataset names, and flag terms referred to organizations.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><code>Pyalex</code> is an open-source library designed to facilitate interaction with the OpenAlex API; see <a href="https://help.openalex.org/hc/en-us/articles/27086501974551-Projects-Using-OpenAlex">https://help.openalex.org/hc/en-us/articles/27086501974551-Projects-Using-OpenAlex</a> for more information. The package manages request formatting and automates compliance with OpenAlex’s “polite pool” rate limits, which restrict the number of requests per minute and impose backoff delays. Pyalex introduced automatic pauses between requests, with a default <code>retry_backoff_factor</code> of 100 milliseconds, to ensure stable and continuous retrieval. This setup enabled systematic querying while adhering to OpenAlex’s usage policies.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><a href="./appendices/app_ipeds.html">IPEDS appendix available here</a><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p><a href="./appendices/app_msi.html">MSI appendix available here</a><a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/laurenchenarides\.github\.io\/compare_scopus_openalex_report\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./workflow/results/compare_pub_data.html" class="pagination-link" aria-label="Step 04: Compare Results">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Step 04: Compare Results</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./conclusions.html" class="pagination-link" aria-label="Conclusions">
        <span class="nav-page-text">Conclusions</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/laurenchenarides/compare_scopus_openalex_report/edit/main/report.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/laurenchenarides/compare_scopus_openalex_report/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This page is built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>